# Copyright © 2026 Kyle J. Cardoza. MIT licensed — see LICENSE.
# SPDX-License-Identifier: MIT
"""A real TLS handshake on FNX through the FIRST-PARTY libtls API.

docs/design/libressl-plan.md §5/L1. LibreSSL is the system SSL library (pin 4.3.2, sha256-pinned
tarball); L0 built it and L1 stages it. `libressl_l1.sh` drives `openssl s_server`/`s_client`, and the
handshake there stalls with the client's `-state` trace stopping at `write client hello A` — which has
TWO readings, because `s_client` multiplexes (it selects on the socket AND on stdin):

  * its own readiness loop is waiting on something the kernel does not report, or
  * the next gap is in the stream path itself.

This case removes the first reading by construction: `libressl_tls_pair.c` performs the handshake through
the `tls_server`/`tls_client` API this project ships, driven the way libtls DOCUMENTS it — a non-blocking
socket with `TLS_WANT_POLLIN`/`TLS_WANT_POLLOUT` handled by a bounded `poll(2)` loop. There is no
`select` of its own in it, and its narration prints every round, so a stall says WHICH readiness never
arrived instead of just hanging.

  * `tls-library-initialises`, `listener-bound`, `peer-forked`, `client-configured`, `client-connect`
      — the setup, and ALL of it passes;
  * `tls-handshake-completed`        — KNOWN BLOCKED (see below);
  * `application-data-flowed`        — KNOWN BLOCKED, same cause;
  * `peer-completed-a-handshake`     — KNOWN BLOCKED, same cause.

WHAT THE NARRATION MEASURES, and it is the whole value of this case today — run it and BOTH SIDES ARE
FOUND WAITING TO READ, neither writing:

    client: round 0 wants POLLIN      -> POLLIN NEVER ARRIVED (5s)
    peer:   round 0 wants POLLIN, round 1 wants POLLIN

So the ClientHello reaches the peer only IN PART and the ServerHello never comes back at all. It is not
`select`-versus-blocking (this program has no `select` of its own), and it is not the plain stream path
(`kernel_loopback_tcp` moves 27 bytes each way with blocking I/O). The next instrument is libtls's own
`tls_config_set_bio` callback, which logs every TLS read and write WITH ITS SIZE — the byte flow is the
thing left to see.

The certificate and key are generated by `libressl_tls_pair.sh` (via `openssl req`), which then execs the
probe so the probe owns the check tally.

AND THE THREE BLOCKED CHECKS ARE ASSERTED AS BLOCKED rather than xfailed away:
`known-blocked-checks-still-blocked` FAILS with an instruction the moment the handshake starts working, so
the limitation cannot rot silently. That is §45-Y's pattern in this harness's own idiom.
"""

import re

from harness import BaseCase

PROBE = "/System/Shared/tests/libressl_tls_pair.sh"
CHECKS = ("tls-library-initialises", "listener-bound", "peer-forked", "client-configured",
          "client-connect", "tls-handshake-completed", "application-data-flowed",
          "peer-completed-a-handshake")
# The three the stall takes with it. Named here so that "blocked" is a claim this case CHECKS rather
# than something it tolerates.
BLOCKED = ("tls-handshake-completed", "application-data-flowed", "peer-completed-a-handshake")


class Case(BaseCase):
    title = "libtls on the guest: the handshake as far as it gets (L1's substance, known blocked)"
    tier = "fast"
    # Self-contained: its own listener, its own peer, its own certificate. A reused guest answers the
    # same, and every wait in the probe is bounded by its watchdog.
    shared_session = True
    timeout = 300

    def run(self, ctx):
        ctx.require_guest_file("libressl_tls_pair.sh")
        session = ctx.boot()
        ready = session.shell_ready(150)
        self.check("shell-ready", ready,
                   "the serial console has a shell" if ready
                   else "no shell; guest tail: " + session.tail())
        if not ready:
            return

        mark = len(session.log_text())
        session.run("sh %s; echo LIBRESSL-PAIR-STATUS=$?" % PROBE)
        out = session.output_since(mark)
        for line in out.splitlines():
            if line.startswith("LIBRESSL-PAIR"):
                self.note(line)

        done = "LIBRESSL-PAIR DONE" in out
        self.check("probe-ran", done,
                   "the probe reached its end marker" if done
                   else "no LIBRESSL-PAIR DONE; output tail: " + out.strip()[-400:])
        if not done:
            return

        # EVERY CHECK THAT IS NOT KNOWN BLOCKED MUST PASS.
        missing = [c for c in CHECKS
                   if c not in BLOCKED
                   and not re.search(r"^LIBRESSL-PAIR %s ok$" % re.escape(c), out, re.M)]
        self.check("every-expected-check-passed", not missing,
                   ("all %d checks outside the known block reported ok"
                    % (len(CHECKS) - len(BLOCKED))) if not missing
                   else "%d missing: %s" % (len(missing), ", ".join(missing)))

        # ...AND THE KNOWN BLOCK MUST STILL BE BLOCKED. This is the check that flips: the day the
        # handshake completes, it fails and says what to delete.
        unblocked = [c for c in BLOCKED
                     if re.search(r"^LIBRESSL-PAIR %s ok$" % re.escape(c), out, re.M)]
        self.check("known-blocked-checks-still-blocked", not unblocked,
                   "THE HANDSHAKE COMPLETES NOW - remove BLOCKED from this case and the L1 limitation "
                   "from docs/design/libressl-plan.md" if unblocked
                   else "still blocked as recorded: " + ", ".join(BLOCKED))

        # AND THE PROBE'S OWN TALLY MUST ACCOUNT FOR EVERY CHECK, so a check that stopped being reported
        # at all cannot read as a pass.
        tally = re.search(r"LIBRESSL-PAIR RESULT ok=(\d+) fail=(\d+)", out)
        self.check("tally-accounts-for-every-check",
                   bool(tally) and int(tally.group(1)) + int(tally.group(2)) == len(CHECKS),
                   "the probe's tally: %s" % (tally.group(0) if tally else "missing"))
