# Copyright © 2026 Kyle J. Cardoza. MIT licensed — see LICENSE.
# SPDX-License-Identifier: MIT
"""A real TLS handshake on FNX through the FIRST-PARTY libtls API — L1 IS MET.

docs/design/libressl-plan.md §5/L1. LibreSSL is the system SSL library (pin 4.3.2, sha256-pinned
tarball); L0 built it and L1 stages it. `libressl_l1.sh` drives `openssl s_server`/`s_client`, and the
handshake there stalls with the client's `-state` trace stopping at `write client hello A` — which has
TWO readings, because `s_client` multiplexes (it selects on the socket AND on stdin):

  * its own readiness loop is waiting on something the kernel does not report, or
  * the next gap is in the stream path itself.

This case removes the first reading by construction: `libressl_tls_pair.c` performs the handshake through
the `tls_server`/`tls_client` API this project ships, driven the way libtls DOCUMENTS it — a non-blocking
socket with `TLS_WANT_POLLIN`/`TLS_WANT_POLLOUT` handled by a bounded `poll(2)` loop. There is no
`select` of its own in it, and its narration prints every round, so a stall says WHICH readiness never
arrived instead of just hanging.

  * `tls-library-initialises`, `listener-bound`, `peer-forked`, `client-configured`, `client-connect`
      — the setup, and ALL of it passes;
  * `tls-handshake-completed`        — **ok: a TLSv1.3 handshake completes**;
  * `application-data-flowed`        — **ok: a request goes out through the tunnel and a reply
                                        comes back** (`HTTP/1.0 200 ok` + the payload);
  * `peer-completed-a-handshake`     — **ok: the peer's own account, exit code 0**.

HOW IT WAS BLOCKED, AND WHAT FOUND IT — this case went green only after a KERNEL bug was fixed, and the
instrument that found it is worth keeping. The handshake stalled with both sides waiting to read; the
libtls BIO seam (`tls_connect_cbs`/`tls_accept_cbs`, which take the read and write functions so the
transport is ours) then logged the byte flow and showed it exactly:

    client: WRITE took   307      <- the whole ClientHello, in one write
    peer:   READ  got    5        <- the peer read only the record header
    peer:   READ  wants 302       <- and the other 302 bytes were GONE

`net/ipv4.c` (and `net/unix.c`) read `MIN(p->len - p->offset, count)` bytes — advancing `p->offset` for
partial reads — and then dequeued and FREED the packet REGARDLESS, destroying the unread remainder. A
stream socket owes its reader the rest. With that fixed the log reads `READ wants 122 got 122`,
`wants 710 got 710`, …, and the handshake completes. `kernel_loopback_tcp` had missed it because its read
asked for at least as much as the peer wrote: a partial read was the one case it did not cover.

The certificate and key are generated by `libressl_tls_pair.sh` (via `openssl req`), which then execs the
probe so the probe owns the check tally.

THE WAY IT WAS HELD WHILE BLOCKED IS WORTH KEEPING IN MIND: the three checks were ASSERTED AS BLOCKED
rather than xfailed away, and that check FAILED with an instruction ("THE HANDSHAKE COMPLETES NOW -
remove BLOCKED …") the moment the kernel was fixed. That is §45-Y's pattern in this harness's own idiom,
and this is the second time in this plan that it has paid off by announcing its own obsolescence.
"""

import re

from harness import BaseCase

PROBE = "/System/Shared/tests/libressl_tls_pair.sh"
CHECKS = ("tls-library-initialises", "listener-bound", "peer-forked", "client-configured",
          "client-connect", "tls-handshake-completed", "application-data-flowed",
          "peer-completed-a-handshake")
# NOTHING IS BLOCKED ANY MORE. The tuple stays, empty and named, because the check that read it proved
# its worth: it announced its own obsolescence when the kernel fix landed.
BLOCKED = ()


class Case(BaseCase):
    title = "libtls on the guest: the handshake as far as it gets (L1's substance, known blocked)"
    tier = "fast"
    # Self-contained: its own listener, its own peer, its own certificate. A reused guest answers the
    # same, and every wait in the probe is bounded by its watchdog.
    shared_session = True
    timeout = 300

    def run(self, ctx):
        ctx.require_guest_file("libressl_tls_pair.sh")
        session = ctx.boot()
        ready = session.shell_ready(150)
        self.check("shell-ready", ready,
                   "the serial console has a shell" if ready
                   else "no shell; guest tail: " + session.tail())
        if not ready:
            return

        mark = len(session.log_text())
        session.run("sh %s; echo LIBRESSL-PAIR-STATUS=$?" % PROBE)
        out = session.output_since(mark)
        for line in out.splitlines():
            if line.startswith("LIBRESSL-PAIR"):
                self.note(line)

        done = "LIBRESSL-PAIR DONE" in out
        self.check("probe-ran", done,
                   "the probe reached its end marker" if done
                   else "no LIBRESSL-PAIR DONE; output tail: " + out.strip()[-400:])
        if not done:
            return

        # EVERY CHECK MUST PASS — there is no blocked set any more.
        missing = [c for c in CHECKS
                   if c not in BLOCKED
                   and not re.search(r"^LIBRESSL-PAIR %s ok$" % re.escape(c), out, re.M)]
        self.check("every-check-passed", not missing,
                   "all %d checks reported ok" % len(CHECKS) if not missing
                   else "%d missing: %s" % (len(missing), ", ".join(missing)))

        # AND THE PROBE'S OWN TALLY MUST ACCOUNT FOR EVERY CHECK, so a check that stopped being reported
        # at all cannot read as a pass.
        tally = re.search(r"LIBRESSL-PAIR RESULT ok=(\d+) fail=(\d+)", out)
        self.check("tally-accounts-for-every-check",
                   bool(tally) and int(tally.group(1)) + int(tally.group(2)) == len(CHECKS),
                   "the probe's tally: %s" % (tally.group(0) if tally else "missing"))
