compile64:
	@rm -rf .build/64
	@for n in kernel kernel/syscalls mm fs drivers/char drivers/block drivers/pci drivers/video net lib ; do \
		for f in $$(find $$n -name '*.c') ; do \
			o=".build/64/$${f%.c}.o" ; \
			mkdir -p "$$(dirname "$$o")" ; \
			$(CC64) -c -o "$$o" "$$f" || exit 1 ; \
		done ; \
	done
	@echo "compile64: all C sources compile clean as -m64 (no link)"

# 64-bit kernel build flags (long mode). -march must be x86-64, not i386.
# The EFI stub MUST be position-independent (-fPIC): UEFI loads the PE32+
# image at an arbitrary address, and PE base relocations cannot fix up the
# absolute 32-bit immediates that -fno-pie would emit for string literals.
# -fno-semantic-interposition keeps references to our own globals direct
# (RIP-relative) so no GOT is needed in the PE.
CC64K = $(CLANG19) -m64 -march=x86-64 $(LANG) -D__KERNEL__ -I$(INCLUDE) -O2 \
	-fPIC -fno-semantic-interposition -fno-common -ffreestanding \
	-mno-red-zone -mno-sse -mno-sse2 -fno-asynchronous-unwind-tables \
	-fno-stack-protector -Wall -Wstrict-prototypes \
	-DCONFIG_FS_MINIX $(M6DEBUG)

# FNX: PE32+ UEFI application (EFI stub boot). See docs/port-longmode-uefi.txt.
# M4-B: the 64-bit kernel is now the REAL FNX kernel + kernel64 primitives;
# 'build64' builds that. The standalone stub/demo kernel (M1-M4-A demos) is
# kept as 'buildfnxdemo'.
build64: buildfnx

buildfnxdemo: .build/64/fnxdemo.efi

.build/64/fnxdemo.efi: kernel/boot64/efi_stub.c kernel/boot64/main64.c kernel/boot64/paging64.c kernel/boot64/mm64.c kernel/boot64/idt64.c kernel/boot64/gdt64.c kernel/boot64/irq64.c kernel/boot64/msix64.c kernel/boot64/sched64.c kernel/boot64/switch64.S include/fnx/efi.h kernel/boot64/serial64.h
	@mkdir -p .build/64
	$(CC64K) -c -o .build/64/efi_stub.o kernel/boot64/efi_stub.c
	$(CC64K) -c -o .build/64/main64.o kernel/boot64/main64.c
	$(CC64K) -c -o .build/64/paging64.o kernel/boot64/paging64.c
	$(CC64K) -c -o .build/64/mm64.o kernel/boot64/mm64.c
	$(CC64K) -c -o .build/64/idt64.o kernel/boot64/idt64.c
	$(CC64K) -c -o .build/64/gdt64.o kernel/boot64/gdt64.c
	$(CC64K) -c -o .build/64/irq64.o kernel/boot64/irq64.c
	$(CC64K) -c -o .build/64/msix64.o kernel/boot64/msix64.c
	$(CC64K) -c -o .build/64/sched64.o kernel/boot64/sched64.c
	$(CC64K) -c -o .build/64/probe64.o kernel/boot64/probe64.c
	$(CLANG19) -c -o .build/64/switch64.o kernel/boot64/switch64.S
	$(LD) -m i386pep --entry efi_main --image-base 0x1000000 -o $@ \
		.build/64/efi_stub.o .build/64/main64.o .build/64/paging64.o .build/64/mm64.o .build/64/idt64.o .build/64/gdt64.o .build/64/irq64.o .build/64/sched64.o .build/64/probe64.o .build/64/switch64.o
	$(LLVM_OBJCOPY) --remove-section .comment --subsystem=efi_application $@
	@echo "build64: $@ ready (PE32+ EFI application)"

# M4-B: 64-bit build of the REAL FNX kernel (kernel/mm/fs/lib/drivers C
# sources) linked with the kernel64 primitives (paging64/gdt64/idt64/irq64)
# and the EFI stub. The real sources are compiled -m64 with
# -fvisibility=hidden so extern globals (kstat, current, ...) resolve
# PC-relative instead of via the GOT (which ld -m i386pep mishandles).
# gcc 14.x AND clang 19 with -fPIC + -fvisibility=hidden emit
# `mov sym@GOTPCREL(%rip),%rax` instead of `lea sym(%rip),%rax` for extern
# DATA addresses; patch_pic_data.py fixes the one-byte opcode (0x8b -> 0x8d)
# in the objects (see the pattern rule below for the clang details).
CC64R = $(CC64K) -fvisibility=hidden -MMD -MP
REALDIR = .build/64real
OBJDIR64 = .build/64
# kernel/boot64 (the UEFI boot half) is excluded: it compiles with CC64K
# into .build/64 (the EFI app), never with the real kernel's CC64R.
REALSRCS = $(shell find kernel mm fs lib drivers net -name '*.c' 2>/dev/null | grep -v 'font-lat9-' | grep -v '^kernel/boot64/')
REALOBJS = $(patsubst %.c,$(REALDIR)/%.o,$(REALSRCS))
# dependency files (.d) generated by -MMD -MP: one per object, so a change
# to any header (e.g. include/fnx/process.h) rebuilds exactly the objects
# that include it. Previously a header edit silently left mixed struct
# sizes across .o files (the struct-proc boot crash) unless the whole
# .build/64real tree was removed.
REALDEPS = $(patsubst %.o,%.d,$(REALOBJS))

# gcc 14.x with -fPIC -fvisibility=hidden emits `mov sym(%rip),%rax` instead
# of `lea sym(%rip),%rax` for extern DATA addresses; patch_pic_data.py fixes
# the one-byte opcode in the objects (0x8b -> 0x8d).
PATCH_PIC = tools/patch_pic_data.py

K64SRCS = kernel/boot64/efi_stub.c kernel/boot64/main64.c kernel/boot64/paging64.c kernel/boot64/mm64.c kernel/boot64/idt64.c kernel/boot64/gdt64.c kernel/boot64/irq64.c kernel/boot64/msix64.c kernel/boot64/sched64.c kernel/boot64/probe64.c kernel/boot64/user64.c kernel/boot64/kreal64.c kernel/boot64/asm64.c kernel/boot64/sections64.c kernel/boot64/initrd64.c kernel/boot64/switch64.S kernel/boot64/init_trampoline64.S
K64OBJS = $(patsubst kernel/boot64/%.c,$(OBJDIR64)/%.o,$(filter %.c,$(K64SRCS))) \
          $(patsubst kernel/boot64/%.S,$(OBJDIR64)/%.o,$(filter %.S,$(K64SRCS)))
# PATCH_PIC only applies to the C-compiled objects (the .S ones are asm)
K64PICOBJS = $(patsubst kernel/boot64/%.c,$(OBJDIR64)/%.o,$(filter %.c,$(K64SRCS)))
K64DEPS = $(patsubst %.o,%.d,$(K64PICOBJS))

buildfnx: .build/64/fnx.efi toolchain-gate

.build/64/fnx.efi: $(REALOBJS) $(K64OBJS) include/fnx/efi.h kernel/boot64/serial64.h
	@mkdir -p .build/64
	python3 $(PATCH_PIC) $(K64PICOBJS) > /dev/null
	$(LD) -m i386pep --entry efi_main --image-base 0x1000000 -o $@ \
		$(REALOBJS) \
		$(K64OBJS)
	$(LLVM_OBJCOPY) --remove-section .comment --subsystem=efi_application $@
	@echo "buildfnx: $@ ready (PE32+ EFI application, REAL kernel + kernel64 primitives)"

$(REALDIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC64R) -c -o $@ $<
	# PATCH_PIC: with -fPIC both gcc-14 AND clang address hidden-extern
	# data via R_X86_64_REX_GOTPCRELX (mov sym@GOTPCREL); GNU ld's PE
	# link cannot relax that (no GOT), so the tool rewrites the mov to a
	# lea (direct PC32, resolved by ld). Verified required for clang too
	# - without it mem_init's _last_data_addr access #GPs on a zeroed GOT
	# slot (see docs/llvm-clang-toolchain-plan.md M3).
	python3 $(PATCH_PIC) $@

# pull in the generated header dependencies (-MMD -MP wrote the .d files)
-include $(REALDEPS) $(K64DEPS)

# kernel64 primitives + EFI stub: pattern rule with header deps too.
# Uses CC64R (with -fvisibility=hidden -MMD -MP) exactly like the original
# inline compiles in the .efi rule.
# PATCH_PIC is applied once in the .efi rule (not here), matching the
# original single-pass build.
$(OBJDIR64)/%.o: kernel/boot64/%.c
	@mkdir -p $(OBJDIR64)
	$(CC64R) -c -o $@ $<

# kreal64.c bakes the UEFI boot cmdline (kernel/boot64/kreal64.c). A forced
# recovery boot appends the param at build time: make buildfnx \
#   FNX_RECOVERY_PARAM=1   (rm .build/64/kreal64.o first)
$(OBJDIR64)/kreal64.o: kernel/boot64/kreal64.c
	@mkdir -p $(OBJDIR64)
	$(CC64R) -c -o $@ $< $(if $(FNX_RECOVERY_PARAM),-DFNX_RECOVERY_PARAM,)

$(OBJDIR64)/%.o: kernel/boot64/%.S
	@mkdir -p $(OBJDIR64)
	$(CLANG19) -c $(M6DEBUG) -o $@ $<
