/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define VENDOR_MAN_VERSION "Version 21.1.24"

#define VENDOR_NAME "The X.Org Foundation"

#define VENDOR_NAME_SHORT "X.Org"

#define VENDOR_RELEASE 12101024

#define VENDOR_WEB "http://wiki.x.org"

