/*
 * Copyright © 2026 Kyle J. Cardoza. MIT licensed — see LICENSE.
 * SPDX-License-Identifier: MIT
 */
/*
 * NSNumber.m — the boxed scalar of the whole C-type matrix.
 *
 * MANUAL OWNERSHIP: nothing here implements -retain/-release.
 *
 * THE 15-WAY MATRIX IS GENERATED BY MACROS, a deliberate exception to spelling
 * everything out: it is 15 creation methods, 15 initialisers and 15 accessors
 * that differ ONLY in their C type, and hand-writing that is 45 chances to fumble
 * a cast. The ENCODING comes from @encode — the compiler's own answer — so
 * -objCType cannot drift from the type it stores.
 *
 * The store goes to the widest member that holds it: signed types to
 * _signedValue, unsigned to _unsignedValue, floating to _doubleValue (a float
 * round-trips exactly through a double).
 */

#import <Foundation/NSNumber.h>
#import <Foundation/NSDecimalNumber.h>
#include <string.h>
#include <stdlib.h>
#import <Foundation/NSString.h>
#include <stdio.h>

#define FN_NUMBER_NEW(NAME, TYPE, FIELD, CAST) \
	+ (NSNumber *)numberWith##NAME:(TYPE)value \
	{ \
		return [[self alloc] initWith##NAME:value]; \
	} \
	- (id)initWith##NAME:(TYPE)value \
	{ \
		self = [super init]; \
		if (self != nil) { \
			_value.FIELD = (CAST)value; \
			_kind = (unsigned char)(*@encode(TYPE)); \
		} \
		return self; \
	}

#define FN_NUMBER_GET(NAME, TYPE) \
	- (TYPE)NAME##Value \
	{ \
		switch (_kind) { \
		case 'C': case 'S': case 'I': case 'L': case 'Q': \
			return (TYPE)_value._unsignedValue; \
		case 'f': case 'd': \
			return (TYPE)_value._doubleValue; \
		default: \
			return (TYPE)_value._signedValue; \
		} \
	}

/* Private helpers, declared where they are used. */
@interface NSNumber ()
- (int)isFloating;
- (int)isUnsigned;
@end

@implementation NSNumber

/* creation + init */
FN_NUMBER_NEW(Bool, BOOL, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(Char, char, _signedValue, long long)
FN_NUMBER_NEW(Short, short, _signedValue, long long)
FN_NUMBER_NEW(Int, int, _signedValue, long long)
FN_NUMBER_NEW(Long, long, _signedValue, long long)
FN_NUMBER_NEW(LongLong, long long, _signedValue, long long)
FN_NUMBER_NEW(Integer, NSInteger, _signedValue, long long)
FN_NUMBER_NEW(UnsignedChar, unsigned char, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(UnsignedShort, unsigned short, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(UnsignedInt, unsigned int, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(UnsignedLong, unsigned long, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(UnsignedLongLong, unsigned long long, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(UnsignedInteger, NSUInteger, _unsignedValue, unsigned long long)
FN_NUMBER_NEW(Float, float, _doubleValue, double)
FN_NUMBER_NEW(Double, double, _doubleValue, double)

/* the same matrix as accessors */
FN_NUMBER_GET(char, char)
FN_NUMBER_GET(short, short)
FN_NUMBER_GET(int, int)
FN_NUMBER_GET(long, long)
FN_NUMBER_GET(longLong, long long)
FN_NUMBER_GET(integer, NSInteger)
FN_NUMBER_GET(unsignedChar, unsigned char)
FN_NUMBER_GET(unsignedShort, unsigned short)
FN_NUMBER_GET(unsignedInt, unsigned int)
FN_NUMBER_GET(unsignedLong, unsigned long)
FN_NUMBER_GET(unsignedLongLong, unsigned long long)
FN_NUMBER_GET(unsignedInteger, NSUInteger)
FN_NUMBER_GET(float, float)
FN_NUMBER_GET(double, double)

/*
 * -boolValue is NORMALISED and therefore cannot come from the accessor macro: in
 * this toolchain BOOL is an 8-bit type, so a plain cast of 42 answers 42 rather
 * than YES. Cocoa's rule is "non-zero is true" — and the F2 check that guards it
 * caught exactly this, which is the whole point of keeping the older checks.
 */
- (BOOL)boolValue
{
	return ([self doubleValue] != 0.0 || [self longLongValue] != 0) ? YES : NO;
}

- (NSString *)stringValue
{
	return [self description];
}

- (NSString *)descriptionWithLocale:(id)locale
{
	(void)locale;
	return [self description];
}

- (const char *)objCType
{
	/*
	 * A STRING LITERAL PER KIND, never one shared buffer: two -objCType calls in
	 * one expression would otherwise alias — the same trap F1's tagged strings
	 * fell into, where the materialised buffer made equal-length strings compare
	 * equal to themselves.
	 */
	switch (_kind) {
	case 'C': return @encode(unsigned char);
	case 's': return @encode(short);
	case 'S': return @encode(unsigned short);
	case 'i': return @encode(int);
	case 'I': return @encode(unsigned int);
	case 'l': return @encode(long);
	case 'L': return @encode(unsigned long);
	case 'q': return @encode(long long);
	case 'Q': return @encode(unsigned long long);
	case 'f': return @encode(float);
	case 'd': return @encode(double);
	case 'c': return @encode(char);
	default:  return @encode(BOOL);
	}
}

- (BOOL)isEqualToNumber:(NSNumber *)other
{
	if (other == nil) {
		return NO;
	}
	if (other == self) {
		return YES;
	}
	/*
	 * Two INTEGERS compare as integers: as doubles they would agree above 2^53
	 * and call two different numbers equal. Crossing the signed/unsigned line
	 * compares in the wider unsigned domain, which is what makes -1 (int) equal
	 * ULLONG_MAX — and -hash below canonicalises the same way, so equal numbers
	 * still hash alike.
	 */
	if (![self isFloating] && ![other isFloating]) {
		if ([self isUnsigned] || [other isUnsigned]) {
			return [self unsignedLongLongValue] ==
			       [other unsignedLongLongValue];
		}
		return [self longLongValue] == [other longLongValue];
	}
	return [self doubleValue] == [other doubleValue];
}

/* THE DECIMAL BRIDGE (W3). Appledocuments THAT a conversion happens and nothing about how, so this is the
 * rule: an integer converts EXACTLY (its digits are built from the stored scalar), and a DOUBLE converts
 * through its SHORTEST ROUND-TRIPPING decimal form — the notation a reader of that double would write.
 * The loop is that definition, spelled out: the first precision whose decimal text reads back as the same
 * double, which is at most 17 and is what makes 1.5 become 1.5 rather than 1.4999999999999999. */
- (NSDecimal)decimalValue
{
	NSDecimal result;
	char text[64];
	int i;

	if (_kind == 'f' || _kind == 'd') {
		int precision;

		for (precision = 1; precision <= 17; precision++) {
			snprintf(text, sizeof text, "%.*g", precision, _value._doubleValue);
			if (strtod(text, NULL) == _value._doubleValue) {
				break;
			}
		}
		return [[NSDecimalNumber decimalNumberWithString:[NSString stringWithUTF8String:text]]
			decimalValue];
	}
	result._isNaN = 0;
	result._isCompact = 0;
	{
		unsigned long long magnitude;
		int negative = 0;
		unsigned char digits[24];
		int n = 0;

		if ([self isUnsigned]) {
			magnitude = _value._unsignedValue;
		} else {
			long long signedValue = _value._signedValue;

			negative = (signedValue < 0);
			magnitude = negative ? (unsigned long long)(-(signedValue + 1)) + 1ULL
					     : (unsigned long long)signedValue;
		}
		while (magnitude > 0) {
			digits[n++] = (unsigned char)(magnitude % 10);
			magnitude /= 10;
		}
		for (i = 0; i < n; i++) {
			result._digits[i] = digits[i];
		}
		for (; i < NSDecimalMaxDigits + 1; i++) {
			result._digits[i] = 0;
		}
		result._length = (unsigned char)n;
		result._exponent = 0;
		result._isNegative = (unsigned char)(n > 0 && negative);
	}
	return result;
}

/* THE DECIMAL CASE IS SERVED BY THE SUBCLASS, and the alloc'd receiver is released here: a 44-byte decimal
 * does not fit the scalar union above, and the documented surface is NSNumber's own. Replacing the receiver
 * inside -init is what makes `[[NSNumber alloc] initWithDecimal:d]` and `+numberWithDecimal:` agree. */
- (id)initWithDecimal:(NSDecimal)decimal
{
	[self release];
	return [[NSDecimalNumber alloc] initWithDecimal:decimal];
}

+ (NSNumber *)numberWithDecimal:(NSDecimal)decimal
{
	return [[NSDecimalNumber alloc] initWithDecimal:decimal];
}

- (int)isFloating
{
	return (_kind == 'f' || _kind == 'd');
}

- (int)isUnsigned
{
	return (_kind == 'C' || _kind == 'S' || _kind == 'I' ||
		_kind == 'L' || _kind == 'Q');
}

- (NSComparisonResult)compare:(NSNumber *)other
{
	double a = [self doubleValue];
	double b = [other doubleValue];

	if (a < b) {
		return NSOrderedAscending;
	}
	if (a > b) {
		return NSOrderedDescending;
	}
	return NSOrderedSame;
}

- (BOOL)isEqual:(id)other
{
	if (other == self) {
		return YES;
	}
	if (other == nil || ![other isKindOfClass:[NSNumber class]]) {
		return NO;
	}
	return [self isEqualToNumber:(NSNumber *)other];
}

- (NSUInteger)hash
{
	/* Integral values hash as their integer, in the UNSIGNED domain so that
	 * everything -isEqualToNumber: calls equal hashes alike. */
	unsigned long h = 2166136261UL;

	if (_kind == 'f' || _kind == 'd') {
		double d = _value._doubleValue;
		long long whole = (long long)d;

		if ((double)whole == d) {
			h ^= (unsigned long)whole;
			return h * 16777619UL;
		}
		{
			union {
				double d;
				unsigned long u;
			} bits;

			bits.d = d;
			h ^= bits.u;
			return h * 16777619UL;
		}
	}
	h ^= (unsigned long)([self isUnsigned] ? _value._unsignedValue
					       : (unsigned long long)_value._signedValue);
	return h * 16777619UL;
}

- (NSString *)description
{
	char buffer[48];

	if (_kind == 'f' || _kind == 'd') {
		snprintf(buffer, sizeof buffer, "%g", _value._doubleValue);
	} else if ([self isUnsigned]) {
		snprintf(buffer, sizeof buffer, "%llu", _value._unsignedValue);
	} else {
		snprintf(buffer, sizeof buffer, "%lld", _value._signedValue);
	}
	return [NSString stringWithUTF8String:buffer];
}

/*
 * THE COPYING FAMILY. A number is immutable, so every form returns self — and
 * the conformance is what makes a number usable as a dictionary KEY, since the
 * table copies its keys. Without it the runtime answered nil for the
 * unimplemented -copy and the table filed a phantom entry (the audit's fix A).
 */
- (id)copy
{
	return [self retain];	/* +1: `copy` is an OWNED family (plan §15.2) */
}

- (id)mutableCopy
{
	return [self retain];	/* +1: `copy` is an OWNED family (plan §15.2) */
}

@end
