/*
 * Copyright © 2026 Kyle J. Cardoza. MIT licensed — see LICENSE.
 * SPDX-License-Identifier: MIT
 */
/*
 * NSNumber.m — the boxed scalar of the whole C-type matrix.
 *
 * MANUAL OWNERSHIP: nothing here implements -retain/-release.
 *
 * THE 15-WAY MATRIX IS GENERATED BY MACROS, a deliberate exception to spelling
 * everything out: it is 15 creation methods, 15 initialisers and 15 accessors
 * that differ ONLY in their C type, and hand-writing that is 45 chances to fumble
 * a cast. The ENCODING comes from @encode — the compiler's own answer — so
 * -objCType cannot drift from the type it stores.
 *
 * The store goes to the widest member that holds it: signed types to
 * _signedValue, unsigned to _unsignedValue, floating to _doubleValue (a float
 * round-trips exactly through a double).
 */

#import <Foundation/NSNumber.h>
#import <Foundation/NSDecimalNumber.h>
#include <string.h>
#include <stdlib.h>
#import <Foundation/NSString.h>
#import <Foundation/NSException.h>	/* §63.22: the coder door refuses an archive with no number type */
#import <Foundation/NSCoder.h>		/* §63.22: the coder PRIMITIVES the doors are written over */
#include <stdio.h>

/*
 * THE CONSTRUCTOR CHOOSES THE CLASS, because the class follows the TYPE: the front is payload-free and
 * each concrete class holds one width. A constructor reached on the FRONT (or on AGNumberItems, which is
 * what +alloc answers with) re-routes; reached on a concrete class it is that class's own, generated by
 * AG_NUMBER_INIT below and taking precedence.
 */
#define FN_NUMBER_NEW(NAME, TYPE, CLS) \
	+ (NSNumber *)numberWith##NAME:(TYPE)value \
	{ \
		return [[AGNumber##CLS alloc] initWith##NAME:value]; \
	} \
	- (id)initWith##NAME:(TYPE)value \
	{ \
		[self release]; \
		return [[AGNumber##CLS alloc] initWith##NAME:value]; \
	}

/* THE READER keeps the three-way dispatch the tagged union used, over the primitives instead of a field. */
#define FN_NUMBER_GET(NAME, TYPE) \
	- (TYPE)NAME##Value \
	{ \
		unsigned char kind = [self agKind]; \
		if (kind == 'C' || kind == 'S' || kind == 'I' || kind == 'L' || kind == 'Q') { \
			return (TYPE)[self unsignedLongLongValue]; \
		} \
		if (kind == 'f' || kind == 'd') { \
			return (TYPE)[self doubleValue]; \
		} \
		return (TYPE)[self longLongValue]; \
	}

/* ONE INITIALISER PER (CLASS, TYPE): DECLARATION goes in the @interface, DEFINITION in the
 * @implementation - the first version used one macro for both and emitted method BODIES inside an
 * @interface, which the compiler refused ("expected ';' after method prototype"). */
#define AG_NUMBER_DECL(NAME, TYPE) \
	- (id)initWith##NAME:(TYPE)value;

#define AG_NUMBER_INIT(NAME, TYPE, FIELD, CAST) \
	- (id)initWith##NAME:(TYPE)value \
	{ \
		self = [super init]; \
		if (self != nil) { \
			FIELD = (CAST)value; \
			_kind = (unsigned char)(*@encode(TYPE)); \
		} \
		return self; \
	}

/* Private helpers, declared where they are used. */
@interface NSNumber ()
/* THE PRIMITIVES (§C.3 item 5), declared here because the front's derived methods call them: -objCType
 * and the fifteen conversions dispatch on -agKind, and every read goes through a payload accessor. */
- (unsigned char)agKind;
- (int)isFloating;
- (int)isUnsigned;
@end

/* THE PRIVATE CONCRETE CLASSES (plan §C.3, M4): one per payload width, plus the general instance the
 * door answers with. Each holds its own field and the @encode char it was built as, and answers the four
 * primitives - which is all the front needs from any of them. */
@interface AGNumberItems : NSNumber
@end

@interface AGNumberSigned : NSNumber
{
	long long _signed;
	unsigned char _kind;
}
AG_NUMBER_DECL(Char, char)
AG_NUMBER_DECL(Short, short)
AG_NUMBER_DECL(Int, int)
AG_NUMBER_DECL(Long, long)
AG_NUMBER_DECL(LongLong, long long)
AG_NUMBER_DECL(Integer, NSInteger)
@end

@interface AGNumberUnsigned : NSNumber
{
	unsigned long long _unsigned;
	unsigned char _kind;
}
AG_NUMBER_DECL(UnsignedChar, unsigned char)
AG_NUMBER_DECL(UnsignedShort, unsigned short)
AG_NUMBER_DECL(UnsignedInt, unsigned int)
AG_NUMBER_DECL(UnsignedLong, unsigned long)
AG_NUMBER_DECL(UnsignedLongLong, unsigned long long)
AG_NUMBER_DECL(UnsignedInteger, NSUInteger)
@end

@interface AGNumberFloating : NSNumber
{
	double _floating;
	unsigned char _kind;
}
AG_NUMBER_DECL(Float, float)
AG_NUMBER_DECL(Double, double)
@end

@interface AGNumberBoolean : NSNumber
{
	BOOL _flag;
	unsigned char _kind;
}
AG_NUMBER_DECL(Bool, BOOL)
@end

@implementation NSNumber

/* THE FRONT'S OWN `-agKind`, WHICH THE CONTINUATION ABOVE DECLARES AND WHICH NOBODY HAD DEFINED (§63.22).
 *
 * THIS IS A PRE-EXISTING WARNING THAT THE BUILD CACHE HID, and it was EXPOSED, not caused, by this unit:
 * compiling HEAD's own NSNumber.m warns identically, while `.build/foundation-NSNumber.o` is dated 2026-09-29 -
 * the class-cluster landing - so the file had not been recompiled since the five concrete classes moved their
 * `-agKind` definitions out of it (lines 499/530/561).
 *
 * AND IT IS WHERE THE FRONT'S OWN DERIVED DOORS MEET THE HOLE: `-isFloating` and `-isUnsigned` are defined
 * above, on this class, and BOTH ARE WRITTEN OVER `-agKind` ("derived from the primitive kind, so a subclass
 * answers them correctly for free"). That is the design working as intended for every concrete instance and an
 * INCOMPLETE IMPLEMENTATION for the front itself, which is exactly what clang was saying.
 *
 * SO THE ABSTRACT ANSWER IS THE HONEST ONE: a payload-free front has no kind to report, and inventing one
 * (`'q'`, say) would turn an unanswerable question into a wrong number. Raising keeps the promise the doc
 * comment makes - the SUBCLASS answers - and it changes no behaviour: before this definition the same call
 * raised an unrecognised selector on the very same classes. */
- (unsigned char)agKind
{
	[self doesNotRecognizeSelector:_cmd];
	return 0;
}

/* THE NSCoding DOORS (§63.22). THE PAIR IS THIS CLASS'S OWN, and every arm decodes back THROUGH this class's
 * existing initialisers, so which concrete class a number becomes is decided by the routing that was already
 * here (the front re-routes; a concrete class takes its own) rather than by a second copy of that rule. */
- (void)encodeWithCoder:(NSCoder *)coder
{
	unsigned char kind = [self agKind];
	char type[2];

	/* THE TYPE TRAVELS WITH THE VALUE: `-objCType` "answers with the @encode of the type the number was
	 * CREATED as" (this header), so a box that dropped it would hand back the integer 1 as a double. */
	type[0] = (char)kind;
	type[1] = '\0';
	[coder encodeBytes:(const void *)type length:1 forKey:@"NS.numberType"];
	if (kind == 'f' || kind == 'd') {
		[coder encodeDouble:[self doubleValue] forKey:@"NS.number"];
	} else {
		/* NO `-encodeInt64:` IN THIS LIBRARY'S CODER — only -encodeInteger:, -encodeBool:, -encodeDouble:
		 * and the bytes door — and NSInteger is 64-bit here, so it carries the widest signed payload. */
		[coder encodeInteger:(NSInteger)[self longLongValue] forKey:@"NS.number"];
	}
}

- (id)initWithCoder:(NSCoder *)coder
{
	NSUInteger length = 0;
	const void *stored = [coder decodeBytesForKey:@"NS.numberType" returnedLength:&length];
	char kind;

	if (stored == NULL || length == 0) {
		[NSException raise:NSInvalidArgumentException
			    format:@"NSNumber: the archive carries no number type, so the value's own type is unknown"];
	}
	kind = ((const char *)stored)[0];
	switch (kind) {
	case 'f':
		return [self initWithFloat:(float)[coder decodeDoubleForKey:@"NS.number"]];
	case 'd':
		return [self initWithDouble:[coder decodeDoubleForKey:@"NS.number"]];
	case 'B': case 'c':
		return [self initWithBool:(BOOL)[coder decodeIntegerForKey:@"NS.number"]];
	default:
		return [self initWithLongLong:(long long)[coder decodeIntegerForKey:@"NS.number"]];
	}
}

/* THE DOOR (§C.3 item 1): a concrete class INHERITS this, and `[super alloc]` starts the lookup at
 * NSNumber's superclass with the receiver still being the class that was asked - so the routing happens
 * exactly ONCE, at the front, and every constructor above re-routes from AGNumberItems to the class its
 * TYPE needs. */
+ (id)alloc
{
	if (self != [NSNumber class]) {
		return [super alloc];
	}
	return [AGNumberItems alloc];
}

/*
 * §C.3 item 4: an archiver asks for THIS, never for -class - but ONLY the private concrete classes are
 * hidden. NSNumber HAS a public subclass (NSDecimalNumber), and an unconditional override would rewrite
 * THAT class's name in every archive: measured, not hypothetical - it broke foundation_urlsession_task
 * and foundation_websockettask, which encode numeric values.
 */
- (Class)classForCoder
{
	Class cls = [self class];

	if (cls == [AGNumberItems class] || cls == [AGNumberSigned class] ||
	    cls == [AGNumberUnsigned class] || cls == [AGNumberFloating class] ||
	    cls == [AGNumberBoolean class]) {
		return [NSNumber class];
	}
	return cls;
}

/* creation + init */
FN_NUMBER_NEW(Bool, BOOL, Boolean)
FN_NUMBER_NEW(Char, char, Signed)
FN_NUMBER_NEW(Short, short, Signed)
FN_NUMBER_NEW(Int, int, Signed)
FN_NUMBER_NEW(Long, long, Signed)
FN_NUMBER_NEW(LongLong, long long, Signed)
FN_NUMBER_NEW(Integer, NSInteger, Signed)
FN_NUMBER_NEW(UnsignedChar, unsigned char, Unsigned)
FN_NUMBER_NEW(UnsignedShort, unsigned short, Unsigned)
FN_NUMBER_NEW(UnsignedInt, unsigned int, Unsigned)
FN_NUMBER_NEW(UnsignedLong, unsigned long, Unsigned)
FN_NUMBER_NEW(UnsignedLongLong, unsigned long long, Unsigned)
FN_NUMBER_NEW(UnsignedInteger, NSUInteger, Unsigned)
FN_NUMBER_NEW(Float, float, Floating)
FN_NUMBER_NEW(Double, double, Floating)

/* the same matrix as accessors */
FN_NUMBER_GET(char, char)
FN_NUMBER_GET(short, short)
FN_NUMBER_GET(int, int)
FN_NUMBER_GET(long, long)
FN_NUMBER_GET(longLong, long long)
FN_NUMBER_GET(integer, NSInteger)
FN_NUMBER_GET(unsignedChar, unsigned char)
FN_NUMBER_GET(unsignedShort, unsigned short)
FN_NUMBER_GET(unsignedInt, unsigned int)
FN_NUMBER_GET(unsignedLong, unsigned long)
FN_NUMBER_GET(unsignedLongLong, unsigned long long)
FN_NUMBER_GET(unsignedInteger, NSUInteger)
FN_NUMBER_GET(float, float)
FN_NUMBER_GET(double, double)

/*
 * -boolValue is NORMALISED and therefore cannot come from the accessor macro: in
 * this toolchain BOOL is an 8-bit type, so a plain cast of 42 answers 42 rather
 * than YES. Cocoa's rule is "non-zero is true" — and the F2 check that guards it
 * caught exactly this, which is the whole point of keeping the older checks.
 */
- (BOOL)boolValue
{
	return ([self doubleValue] != 0.0 || [self longLongValue] != 0) ? YES : NO;
}

- (NSString *)stringValue
{
	return [self description];
}

- (NSString *)descriptionWithLocale:(id)locale
{
	(void)locale;
	return [self description];
}

- (const char *)objCType
{
	/*
	 * A STRING LITERAL PER KIND, never one shared buffer: two -objCType calls in
	 * one expression would otherwise alias — the same trap F1's tagged strings
	 * fell into, where the materialised buffer made equal-length strings compare
	 * equal to themselves.
	 */
	switch ([self agKind]) {
	case 'C': return @encode(unsigned char);
	case 's': return @encode(short);
	case 'S': return @encode(unsigned short);
	case 'i': return @encode(int);
	case 'I': return @encode(unsigned int);
	case 'l': return @encode(long);
	case 'L': return @encode(unsigned long);
	case 'q': return @encode(long long);
	case 'Q': return @encode(unsigned long long);
	case 'f': return @encode(float);
	case 'd': return @encode(double);
	case 'c': return @encode(char);
	default:  return @encode(BOOL);
	}
}

- (BOOL)isEqualToNumber:(NSNumber *)other
{
	if (other == nil) {
		return NO;
	}
	if (other == self) {
		return YES;
	}
	/*
	 * Two INTEGERS compare as integers: as doubles they would agree above 2^53
	 * and call two different numbers equal. Crossing the signed/unsigned line
	 * compares in the wider unsigned domain, which is what makes -1 (int) equal
	 * ULLONG_MAX — and -hash below canonicalises the same way, so equal numbers
	 * still hash alike.
	 */
	if (![self isFloating] && ![other isFloating]) {
		if ([self isUnsigned] || [other isUnsigned]) {
			return [self unsignedLongLongValue] ==
			       [other unsignedLongLongValue];
		}
		return [self longLongValue] == [other longLongValue];
	}
	return [self doubleValue] == [other doubleValue];
}

/* THE DECIMAL BRIDGE (W3). Appledocuments THAT a conversion happens and nothing about how, so this is the
 * rule: an integer converts EXACTLY (its digits are built from the stored scalar), and a DOUBLE converts
 * through its SHORTEST ROUND-TRIPPING decimal form — the notation a reader of that double would write.
 * The loop is that definition, spelled out: the first precision whose decimal text reads back as the same
 * double, which is at most 17 and is what makes 1.5 become 1.5 rather than 1.4999999999999999. */
- (NSDecimal)decimalValue
{
	NSDecimal result;
	char text[64];
	int i;

	if ([self agKind] == 'f' || [self agKind] == 'd') {
		int precision;

		for (precision = 1; precision <= 17; precision++) {
			snprintf(text, sizeof text, "%.*g", precision, [self doubleValue]);
			if (strtod(text, NULL) == [self doubleValue]) {
				break;
			}
		}
		return [[NSDecimalNumber decimalNumberWithString:[NSString stringWithUTF8String:text]]
			decimalValue];
	}
	result._isNaN = 0;
	result._isCompact = 0;
	{
		unsigned long long magnitude;
		int negative = 0;
		unsigned char digits[24];
		int n = 0;

		if ([self isUnsigned]) {
			magnitude = [self unsignedLongLongValue];
		} else {
			long long signedValue = [self longLongValue];

			negative = (signedValue < 0);
			magnitude = negative ? (unsigned long long)(-(signedValue + 1)) + 1ULL
					     : (unsigned long long)signedValue;
		}
		while (magnitude > 0) {
			digits[n++] = (unsigned char)(magnitude % 10);
			magnitude /= 10;
		}
		for (i = 0; i < n; i++) {
			result._digits[i] = digits[i];
		}
		for (; i < NSDecimalMaxDigits + 1; i++) {
			result._digits[i] = 0;
		}
		result._length = (unsigned char)n;
		result._exponent = 0;
		result._isNegative = (unsigned char)(n > 0 && negative);
	}
	return result;
}

/* THE DECIMAL CASE IS SERVED BY THE SUBCLASS, and the alloc'd receiver is released here: a 44-byte decimal
 * does not fit the scalar union above, and the documented surface is NSNumber's own. Replacing the receiver
 * inside -init is what makes `[[NSNumber alloc] initWithDecimal:d]` answer an NSDecimalNumber - and the factory
 * that used to stand beside it, +numberWithDecimal:, is GONE (§63.59): Apple's way to build one from an
 * NSDecimal is NSDecimalNumber's +decimalNumberWithDecimal:, which answers the same object. */
- (id)initWithDecimal:(NSDecimal)decimal
{
	[self release];
	return [[NSDecimalNumber alloc] initWithDecimal:decimal];
}

/* Both derived from the primitive kind, so a subclass answers them correctly for free. */
- (int)isFloating
{
	return ([self agKind] == 'f' || [self agKind] == 'd');
}

- (int)isUnsigned
{
	unsigned char kind = [self agKind];

	return (kind == 'C' || kind == 'S' || kind == 'I' || kind == 'L' || kind == 'Q');
}

- (NSComparisonResult)compare:(NSNumber *)other
{
	double a = [self doubleValue];
	double b = [other doubleValue];

	if (a < b) {
		return NSOrderedAscending;
	}
	if (a > b) {
		return NSOrderedDescending;
	}
	return NSOrderedSame;
}

- (BOOL)isEqual:(id)other
{
	if (other == self) {
		return YES;
	}
	if (other == nil || ![other isKindOfClass:[NSNumber class]]) {
		return NO;
	}
	return [self isEqualToNumber:(NSNumber *)other];
}

- (NSUInteger)hash
{
	/* Integral values hash as their integer, in the UNSIGNED domain so that
	 * everything -isEqualToNumber: calls equal hashes alike. */
	unsigned long h = 2166136261UL;

	if ([self agKind] == 'f' || [self agKind] == 'd') {
		double d = [self doubleValue];
		long long whole = (long long)d;

		if ((double)whole == d) {
			h ^= (unsigned long)whole;
			return h * 16777619UL;
		}
		{
			union {
				double d;
				unsigned long u;
			} bits;

			bits.d = d;
			h ^= bits.u;
			return h * 16777619UL;
		}
	}
	h ^= (unsigned long)([self isUnsigned] ? [self unsignedLongLongValue]
					       : (unsigned long long)[self longLongValue]);
	return h * 16777619UL;
}

- (NSString *)description
{
	char buffer[48];

	if ([self agKind] == 'f' || [self agKind] == 'd') {
		snprintf(buffer, sizeof buffer, "%g", [self doubleValue]);
	} else if ([self isUnsigned]) {
		snprintf(buffer, sizeof buffer, "%llu", [self unsignedLongLongValue]);
	} else {
		snprintf(buffer, sizeof buffer, "%lld", [self longLongValue]);
	}
	return [NSString stringWithUTF8String:buffer];
}

/*
 * THE COPYING FAMILY. A number is immutable, so every form returns self — and
 * the conformance is what makes a number usable as a dictionary KEY, since the
 * table copies its keys. Without it the runtime answered nil for the
 * unimplemented -copy and the table filed a phantom entry (the audit's fix A).
 */
- (id)copy
{
	return [self retain];	/* +1: `copy` is an OWNED family (plan §15.2) */
}

- (id)mutableCopy
{
	return [self retain];	/* +1: `copy` is an OWNED family (plan §15.2) */
}

@end


/* ===================================================================================================
 * THE CONCRETE CLASSES (§C.3 items 2, 3 and 8).
 * =================================================================================================== */

@implementation AGNumberItems

/* THE GENERAL INSTANCE `+alloc` ANSWERS WITH: no payload, kind 0, and every read answering zero - which
 * is what `[[NSNumber alloc] init]` has always answered. A constructor re-routes from here to the class
 * its TYPE needs, so this instance is only ever the receiver OF a construction. */
- (unsigned char)agKind
{
	return 0;
}

- (long long)longLongValue
{
	return 0;
}

- (unsigned long long)unsignedLongLongValue
{
	return 0;
}

- (double)doubleValue
{
	return 0.0;
}

@end

@implementation AGNumberSigned

AG_NUMBER_INIT(Char, char, _signed, long long)
AG_NUMBER_INIT(Short, short, _signed, long long)
AG_NUMBER_INIT(Int, int, _signed, long long)
AG_NUMBER_INIT(Long, long, _signed, long long)
AG_NUMBER_INIT(LongLong, long long, _signed, long long)
AG_NUMBER_INIT(Integer, NSInteger, _signed, long long)

- (unsigned char)agKind
{
	return _kind;
}

- (long long)longLongValue
{
	return _signed;
}

- (unsigned long long)unsignedLongLongValue
{
	return (unsigned long long)_signed;
}

- (double)doubleValue
{
	return (double)_signed;
}

@end

@implementation AGNumberUnsigned

AG_NUMBER_INIT(UnsignedChar, unsigned char, _unsigned, unsigned long long)
AG_NUMBER_INIT(UnsignedShort, unsigned short, _unsigned, unsigned long long)
AG_NUMBER_INIT(UnsignedInt, unsigned int, _unsigned, unsigned long long)
AG_NUMBER_INIT(UnsignedLong, unsigned long, _unsigned, unsigned long long)
AG_NUMBER_INIT(UnsignedLongLong, unsigned long long, _unsigned, unsigned long long)
AG_NUMBER_INIT(UnsignedInteger, NSUInteger, _unsigned, unsigned long long)

- (unsigned char)agKind
{
	return _kind;
}

- (long long)longLongValue
{
	return (long long)_unsigned;
}

- (unsigned long long)unsignedLongLongValue
{
	return _unsigned;
}

- (double)doubleValue
{
	return (double)_unsigned;
}

@end

@implementation AGNumberFloating

AG_NUMBER_INIT(Float, float, _floating, double)
AG_NUMBER_INIT(Double, double, _floating, double)

- (unsigned char)agKind
{
	return _kind;
}

- (long long)longLongValue
{
	return (long long)_floating;
}

- (unsigned long long)unsignedLongLongValue
{
	return (unsigned long long)_floating;
}

- (double)doubleValue
{
	return _floating;
}

@end

@implementation AGNumberBoolean

AG_NUMBER_INIT(Bool, BOOL, _flag, BOOL)

/* A boolean answers its flag and the numbers it stands for, which is how one class serves both
 * -boolValue and the fifteen conversions without a special case in the reader. */
- (unsigned char)agKind
{
	return _kind;
}

- (long long)longLongValue
{
	return _flag ? 1 : 0;
}

- (unsigned long long)unsignedLongLongValue
{
	return _flag ? 1ULL : 0ULL;
}

- (double)doubleValue
{
	return _flag ? 1.0 : 0.0;
}

@end
