# -*- coding: utf-8 -*-
"""Fetch each owner's macOS INTRODUCTION VERSION from Apple's own page metadata.

WHY THIS EXISTS: the SDK headers annotate what post-dates 10.0, which makes them sound for CUTTING and unsound for
KEEPING -- MEASURED: NSUserNotification is a 10.8 class and carries NO annotation at all, as do NSXMLDocument (10.4),
NSSortDescriptor (10.3) and NSLocale/NSCalendar/NSDateComponents (10.4). 119 of this tree's 221 headers are unannotated,
so 'no annotation means keep' under-cuts by an unknown amount. Apple's page metadata is authoritative, and this is the
one-time crawl that collects it.

!! THE PATHS COME FROM THE INDEX, NOT FROM THE NAME: `nsurlsession` 404s while `NSURLSession` is a real page, so a slug
built from the class name is a guess. One index fetch yields the whole title -> path map, and only the pages for owners
this tree actually declares are then fetched.

Output: docs/reference/foundation-era.txt -- `Name<TAB>version<TAB>deprecatedAt`, with provenance in a comment header.
Run:    python3 tools/foundation-era-fetch.py [--dry]
"""
import glob, io, json, os, re, sys, time, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_URL = "https://developer.apple.com/tutorials/data/documentation/foundation"
OUT = os.path.join(ROOT, "docs/reference/foundation-era.txt")
HEADERS = os.path.join(ROOT, "userland/Foundation/*.h")
DATA = "https://developer.apple.com/tutorials/data"


def get(url, timeout=60):
    with urllib.request.urlopen(url, timeout=timeout) as fh:
        return json.load(fh)


def index_paths():
    """title -> page path, from the index's own reference table.

    !! KEPT ONLY FOR PROVENANCE: the index endpoint this tree has always used
    (tutorials/data/index/foundation) NOW 404s -- see the note at the top -- so the path is DERIVED PER NAME instead.
    """
    d = get(INDEX_URL, timeout=120)
    out = {}
    for _ident, ref in (d.get("references") or {}).items():
        url = ref.get("url") or ""
        title = ref.get("title")
        if title and url.startswith("/documentation/foundation/"):
            out.setdefault(title, url)
    return out


def slug_candidates(name):
    """!! APPLE'S URL CONVENTION IS INCONSISTENT, SO BOTH ARE TRIED AND MEASURED RATHER THAN ASSUMED:
    `nsitemprovider` resolves while `itemprovider` 404s, and `urlsessionconfiguration` resolves while
    `nsurlsessionconfiguration` 404s. A slug built from the name alone is a guess; two attempts settle it."""
    cands = [name.lower()]
    if name.startswith("NS") and len(name) > 2:
        cands.append(name[2:].lower())
    return cands


def resolve(name):
    """(page path, metadata) for an owner, or (None, None) when neither spelling exists."""
    for slug in slug_candidates(name):
        path = "/documentation/foundation/" + slug
        try:
            d = get(DATA + path + ".json")
        except Exception:
            continue
        return path, (d.get("metadata") or {})
    return None, None


def macos_version(meta):
    for p in (meta.get("platforms") or []):
        if (p.get("name") or "").lower().startswith("macos"):
            return p.get("introducedAt"), p.get("deprecatedAt")
    return None, None


def main():
    dry = "--dry" in sys.argv
    ours = sorted(os.path.basename(p)[:-2] for p in glob.glob(HEADERS))
    print("owners this tree declares: %d" % len(ours))
    if dry:
        print("--dry prints no map: the index endpoint 404s, so paths are resolved per name at fetch time.")
        return 0
    rows, missing, failed = [], [], []
    for i, c in enumerate(ours, 1):
        p, meta = resolve(c)
        if p is None:
            missing.append(c)
            continue
        v, dep = macos_version(meta)
        if v is None:
            missing.append(c + "(no macOS entry)")
        else:
            rows.append((c, v, dep or "-"))
        if i % 25 == 0:
            print("  ... %d/%d" % (i, len(ours)))
        time.sleep(0.12)                      # be a considerate client
    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# Foundation owners, with the macOS version Apple's OWN page metadata introduces them at.\n")
        fh.write("# GENERATED by tools/foundation-era-fetch.py -- do not hand-edit. The generator is kept, as\n")
        fh.write("# every other sweep in this tree keeps its own (the artefact is data; the rule is the code).\n")
        fh.write("# source: %s\n#\n" % INDEX_URL)
        fh.write("# name\tintroducedAt\tmacOS deprecatedAt\n#\n")
        for c, v, dep in sorted(rows):
            fh.write("%s\t%s\t%s\n" % (c, v, dep))
    print("wrote %s: %d owners" % (os.path.relpath(OUT, ROOT), len(rows)))
    print("no page / no macOS entry: %d" % len(missing))
    if missing:
        print("  " + ", ".join(missing))
    if failed:
        print("fetch failures: %d" % len(failed))
        for c, e in failed[:6]:
            print("  %-28s %s" % (c, e))
    return 0


if __name__ == "__main__":
    sys.exit(main())
