#!/usr/bin/env python3
# Copyright © 2026 Kyle J. Cardoza. MIT licensed — see LICENSE.
# SPDX-License-Identifier: MIT
"""§11.2's SECOND MECHANICAL SOURCE: the shipped surface against Apple's documented one.

docs/design/foundation-plan.md §11.2 says the ledger must not depend on anyone
remembering, and names two greppable sources. Source 1 is the probes' own
`excluded` arrays. This is source 2, made mechanical: the whole documented
Foundation surface, one line per symbol, with our status against it, in
docs/reference/foundation-apple-surface.txt.

THE STATUS COLUMN IS THE LEDGER, AND IT HAS THREE VALUES:

  shipped  our public headers DECLARE it — and `--check` fails if they stop.
  open     documented, not deprecated, and not ours. THIS IS THE WORK LIST,
           and `--check` fails if our headers start declaring one without the
           row being flipped — which is the bug class §11.2's source 1 hid for
           months (a probe asserting an ABSENCE asserts a fact about the tree,
           and landing the code does not update it).
  struck   OUT by §11.5, so we neither ship it nor owe it. FIVE grounds, and the
           `why` column says which: Apple DEPRECATES it, it exists ONLY to support
           Swift, it exists only for 32-BIT compatibility, it is a per-release
           OS VERSION constant, or it is DECLINED BY PROJECT DECISION (the user's
           2026-09-20 scope decisions — AppleScript, XPC, Spotlight metadata,
           Bonjour). `--check` REPORTS any struck name that appears in our headers
           and `--strict` FAILS on it: what to do about one is a decision, and a
           decision is a ledger row.

AND A FOURTH EXCLUSION (user, 2026-09-18, amending an earlier exception): API that
exists only for 32-BIT COMPATIBILITY. Zones are the case — the 64-bit runtime
ignores them and this system has no 32-bit compatibility at all — so NSZone and
anything that needs it is removed, and `32-bit-only` is that reason. It is OURS
rather than Apple's: measured, Apple's pages for the zone API report no
deprecation and no unavailability.

AN EXCEPTION MECHANISM EXISTS AND IS EMPTY: REQUIRED_BY_LIVE_API held NSZone until
the amendment revoked it. An entry there is a CHECKED claim (the run fails if our
headers do not declare the name), which is what makes an exception different from
a softened rule.

The three exclusions, each counted rather than silently dropped (the numbers
are written into the surface file's header on every `--refresh`):

  * `method` and `property` — the SELECTOR surface. It is §11.2 source 1's
    business (the probes' inventories), not this file's, and it is the
    dimension source 1 must still grow into.
  * `symbol` — Apple's instance-variable documentation (NSSimpleCString's
    `bytes`, `numBytes`). Not API a class library mirrors.
  * Swift-only overlay spellings — a node whose path says `swift.` is the
    Swift view of an ObjC symbol already counted, or a Swift-only type that
    does not exist in ObjC at all. Excluding them is what keeps this file an
    Objective-C surface.

USAGE

  tools/foundation-sweep.py --check             verify the file against our headers (offline)
  tools/foundation-sweep.py --work-list [KIND]  print the open rows — the ledger's work list
  tools/foundation-sweep.py --unimplemented     DECLARED BY A HEADER, IMPLEMENTED NOWHERE - the report
                                                that keeps a missing method from being a fatal surprise.
                                                --write baselines it into
                                                docs/reference/foundation-unimplemented.txt, where every
                                                line carries a reason: "not implemented yet" is a work
                                                item, anything else is a boundary.
  tools/foundation-sweep.py --refresh           re-read Apple's index and rewrite the surface file
  tools/foundation-sweep.py --families [--write] verify (or rewrite) the plan's family status table

`--refresh` is the ONLY mode that touches the network, and it is deliberately
not part of a build: the build runs `--check`, which is a function of this tree
alone. Apple's index grows, so the file is a DATED MEASUREMENT — §11.3.1
records the date, and `--refresh` is how it is taken again.
"""

import json
import os
import re
import sys
import glob
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SURFACE = os.path.join(ROOT, "docs/reference/foundation-apple-surface.txt")
PLAN = os.path.join(ROOT, "docs/design/foundation-plan.md")
# THE PLAN'S FAMILY TABLE IS GENERATED TOO. It was hand-written once and had drifted in 13 of its 83 rows
# — every one of them a class that had since shipped — which made a status table read as a work queue that
# never moved. It is now a rendering of the ledger, and `--check` fails when it drifts.
FAMILY_BEGIN = ("<!-- GENERATED by tools/foundation-sweep.py --families — do not hand-edit: the "
                "class/protocol roll-up per Apple family, read from the ledger. `--check` fails when it "
                "drifts; members (constants, enum cases, functions) are the ledger's own business and "
                "`--work-list` prints them. -->")
FAMILY_END = "<!-- END GENERATED (families) -->"
HEADERS = os.path.join(ROOT, "userland/Foundation/*.h")
INDEX_URL = "https://developer.apple.com/tutorials/data/index/foundation"

# Kinds this file holds, and the kinds it deliberately does not (see the
# docstring: method/property are source 1's, symbol is Apple's ivars).
KINDS = ("class", "protocol", "macro", "enum", "case", "func", "var", "typealias", "struct")
DROP_KINDS = ("method", "property", "symbol")

# Symbols whose page lives outside this framework's documentation but which ARE
# this framework's own API: NSObject, the root class, is documented with the
# Objective-C runtime. Everything else outside /documentation/foundation/ is
# another framework's — see the cross-framework note in walk().
KEEP_ELSEWHERE = ("NSObject",)

STATUS_SHIPPED = "shipped"
STATUS_OPEN = "open"
STATUS_STRUCK = "struck"


def public_header_text():
    """Every public header with comments stripped, so a name mentioned in prose
    is never mistaken for a name declared."""
    text = []
    for path in sorted(glob.glob(HEADERS)):
        body = open(path, encoding="utf-8", errors="replace").read()
        body = re.sub(r"/\*.*?\*/", " ", body, flags=re.S)
        body = re.sub(r"//[^\n]*", " ", body)
        text.append(body)
    return "\n".join(text)


def declared(kind, name, text):
    """Does our surface DECLARE this name?

    TWO RULES, AND THE SECOND ONE WAS LEARNED FROM A WRONG ANSWER. A class is an
    @interface and a protocol is an @protocol — the form IS the API there, so
    those two are exact.

    FOR EVERY OTHER KIND THE FORM IS NOT THE CONTRACT, and demanding Apple's
    form produced a false `open` on the first run: Apple documents `NSNotFound`
    as a VARIABLE and this library declares it as a #define, so the row claimed
    work that is already done. §11 already says an invisible implementation
    choice is not a difference; a constant is a constant to a caller whether it
    arrives as a macro, a typedef or an `extern` var. So the other kinds share
    one test — "declared as ANYTHING" — and what `open` means is that the NAME
    does not occur in a declaration at all.

    That test is still not "the name appears somewhere": comments are stripped
    first, and each alternative is a declaration form (a #define, a typedef's
    declarator, an enum body member, a variable declarator, a prototype)."""
    n = re.escape(name)
    if kind == "class":
        return re.search(r"@interface\s+" + n + r"\b", text)
    if kind == "protocol":
        return re.search(r"@protocol\s+" + n + r"\b", text)
    any_form = (
        r"#\s*define\s+" + n + r"\b"                       # a macro
        # A TYPEDEF DECLARATOR, INCLUDING A BLOCK OR FUNCTION-POINTER ONE (§62.23): `typedef void (^NAME)(id);`
        # ends in `)`, so a matcher that insisted on `;` after the name MISSED every block typedef — which is how
        # NSItemProviderCompletionHandler and NSItemProviderLoadHandler stayed "open" while being declared here.
        r"|typedef[^;]*\b" + n + r"\s*[;)]"
        r"|NS_ENUM\s*\(\s*[^,]+,\s*" + n + r"\s*\)"        # an NS_ENUM
        r"|NS_OPTIONS\s*\(\s*[^,]+,\s*" + n + r"\s*\)"     # an NS_OPTIONS
        r"|\b" + n + r"\s*[=,}]"                           # an enum member
        r"|struct\s+" + n + r"\b"                          # a struct tag
        r"|^[A-Za-z_][\w \t\*]*\b" + n + r"\s*\([^;{]*\)\s*[;{]"  # prototype or definition
        r"|\b" + n + r"\s*;"                               # a variable declarator
    )
    return re.search(any_form, text, re.M | re.S)


# A name Apple gives a Swift-interop annotation. These EXIST ONLY TO SUPPORT
# SWIFT: they are read by the Swift importer and mean nothing to an Objective-C
# caller. §11.5's third exclusion (user, 2026-09-18): out, like deprecated API.
SWIFT_INTEROP_RE = re.compile(r"(^|_)SWIFT(_|$)")

# ...and what an Objective-C name looks like, which is how a Swift-only TYPE is
# told from an ObjC one. Foundation's Objective-C surface is NS-prefixed or an
# upper-case C name; the Swift-only additions to the framework do not bother
# (ProgressManager, ProgressReporter, Subprogress). MEASURED ON 2026-09-18: the
# ObjC navigator carries ZERO symbols of the second kind — every `swift.` page in
# it names an ObjC symbol — so this test is a guard rather than a filter today.
def is_objc_shaped(name):
    return name.startswith("NS") or (name.isupper() and len(name) > 3)


# §11.5's FOURTH EXCLUSION (user, 2026-09-18, amending the NSZone decision):
# "zones are unsupported on 64-bit Apple, and are kept only for 32-bit
# compatibility, which we don't have to worry about. Amendment: NSZone and
# anything that needs it is removed."
#
# APPLE SAYS THIS IN PROSE RATHER THAN IN METADATA, which is why the reason is its
# own and not `deprecated`. The zone pages all read `introducedAt 10.0,
# deprecated: false, unavailable: false` — there is NO deprecation flag to key
# on, so `deprecated` would be this project inventing an Apple fact. But the
# NSZone page's own discussion states the rule in words:
#
#   "Zones are ignored on iOS and 64-bit runtime in macOS. You should not use zones in current development."
#        (developer.apple.com/documentation/foundation/nszone)
#
# THAT is Apple saying the family is 32-bit-only functionality, and this system
# has NO 32-BIT COMPATIBILITY AT ALL (the standing doctrine), so its only
# remaining purpose is compatibility this tree will never need.
#
# THE LIST IS NAMED, NOT INFERRED, because Apple's own filing is inconsistent:
# most of the family sits under `Low-Level Utilities / Legacy / Managing Zones`,
# but NSAllocateObject and NSDeallocateObject sit under `Objective-C Runtime /
# Object Allocation and Deallocation` and read OPEN — so the group signal alone
# would have left two zone-taking functions in the work list.
ZONE_API_RE = re.compile(
    r"^NS(Zone\w*|CreateZone|RecycleZone|DefaultMallocZone|AllocateObject|DeallocateObject|AllocateCollectable)$")


def is_32bit_only(row):
    return bool(ZONE_API_RE.match(row["name"]))


# §11.5's SIXTH EXCLUSION (user, 2026-09-19): the PER-RELEASE version constants.
#
# Apple publishes the NAME of each one and not the NUMBER: the page says only
# "Foundation version released in macOS 10.x" (or the iOS equivalent), and its
# meaning is "which Foundation shipped in that Apple OS release" - not a fact
# this system has. They are NOT deprecated: verified against Apple's pages on
# 2026-09-19, where NSFoundationVersionNumber10_0 reads availability
# iOS 2.0+/macOS 10.0+ with no deprecation badge, and the "Foundation Framework
# Version Numbers" page calls the family legacy rather than deprecated. So the
# `deprecated` reason would be this project inventing an Apple fact - the same
# trap the zone rule avoids.
#
# NAMED, NOT INFERRED, and here that is load-bearing: the bare
# `NSFoundationVersionNumber` is the LIVE current-version constant and IS ours
# (declared `extern double`), so a group signal over "Versions and API
# Availability" would have struck it too. The pattern keeps the current version
# and takes only the per-release ones.
VERSION_CONST_RE = re.compile(r"^NSFoundationVersionNumber(10_|_iOS_|_iPhoneOS_)")


def is_per_release_version_constant(row):
    return bool(VERSION_CONST_RE.match(row["name"]))


def struck_reason(row):
    """Why this symbol is OUT, or None. Three exclusions, and the reason travels
    with the row so a struck line can be argued with."""
    if is_32bit_only(row):
        return "32-bit-only"
    if is_per_release_version_constant(row):
        return "os-version-constant"
    if SWIFT_INTEROP_RE.search(row["name"]):
        return "swift-only"
    if row.get("swift") and not is_objc_shaped(row["name"]):
        return "swift-only"
    if apple_says_deprecated(row):
        return "deprecated"
    return None


# THE NAMED EXCEPTION TO §11.5 (user, 2026-09-18): "NSZone is the exception to
# the rule, because it is required by non-deprecated code."
#
# Apple files `NSZone` under `Low-Level Utilities / Legacy`, so the group signal
# strikes it — but the type is the PARAMETER of Apple's LIVE, non-deprecated
# `NSCopying` and `NSMutableCopying` methods (`-copyWithZone:`), which 20-odd
# headers here declare. Striking it would mean deleting those signatures or
# leaving a type undeclared behind them, so it is ours to ship, and the `why`
# column says why instead of the row silently changing side.
#
# AN EXCEPTION IS NOT A HOLE IN THE CHECK: every name here must be DECLARED in
# our headers, and --check fails if one is not. An entry is a claim about the
# tree, and a claim about the tree is verifiable — which is what makes this
# different from a softened rule.
# EMPTY BY DECISION (2026-09-18, later). `NSZone` was the one entry here, on the
# argument that Apple's live NSCopying methods take it as a parameter. The user
# amended that: zones are 32-bit API and this system has no 32-bit
# compatibility, so NSZone and anything that needs it is REMOVED — including the
# exception. The mechanism is kept because an exception has to be a checked claim
# about the tree (see the verification in refresh() and check()), and the next
# person to want one should find it working rather than reinvent it.
REQUIRED_BY_LIVE_API = {}


# §11.5's SEVENTH EXCLUSION (user, 2026-09-20): SCOPE DECLINED BY THE PROJECT.
#
# The user's words, and they are the ground: "We will not be supporting AppleScript at all, so no
# scripting related classes need be implemented. We will not be supporting XPC either. Nor will we
# support Spotlight, we will use a separate library for live queries. Bonjour is removed."
#
# THESE ROWS ARE NOT DEPRECATED AND ARE NOT SWIFT-ONLY. They are documented, live, and deliberately
# OUT — a fourth kind of reason the ledger did not have, recorded rather than hidden because §11's
# fidelity bar is a promise about what this library DOES, and a refusal is a fact about it. Two
# clarifications came with the decision and are encoded here: `NSSpellServer` (the other half of the
# plan unit Spotlight metadata shares) is KEPT, and `NSUserUnixTask` is kept among its three
# declined siblings.
#
# THE ROOTS ARE NAMED, NOT INFERRED, AND THAT IS LOAD-BEARING — the four families are not
# separable by a pattern, in three MEASURED ways:
#
#   * `NSTask` and `NSPipe` share the family label "Low-Level Utilities / Scripts and External
#     Tasks" with the script runners, but they are W6's process and I/O. A family signal would have
#     struck two classes this library still owes.
#   * `Fundamentals / Strings with Metadata` is W10's ATTRIBUTED-STRING family, not Spotlight. A
#     signal keyed on the word "Metadata" would have struck `NSAttributedString`.
#   * `NSHostByteOrder` is the one row of these families this library already SHIPS — a generic
#     byte-order helper Apple files under Net Services rather than the Bonjour service API — so it
#     is KEPT, and striking it would have meant DELETING working code instead of flipping a row.
#
# Striking a root strikes its MEMBERS too (its constants, methods and notification names): a
# constant that exists only to configure a class this library refuses is not independently owed.
DECLINED_ROOTS = frozenset((
    # AppleScript and the Apple-event layer, with the scripting support the model layer carries.
    "NSAppleEventDescriptor", "NSAppleEventManager", "NSAppleScript", "NSClassDescription",
    "NSCloneCommand", "NSCloseCommand", "NSCountCommand", "NSCreateCommand", "NSDeleteCommand",
    "NSExistsCommand", "NSGetCommand", "NSMoveCommand", "NSQuitCommand", "NSScriptClassDescription",
    "NSScriptCoercionHandler", "NSScriptCommand", "NSScriptCommandDescription",
    "NSScriptExecutionContext", "NSScriptSuiteRegistry", "NSSetCommand",
    # THE OBJECT-PATH MACHINERY: a specifier names a position in another application's object graph,
    # which exists only to serve an Apple event. TWO FAMILIES, both UNMIXED (measured: every row in
    # each is owned by one of these classes and none of them ships), which is why they are listed as
    # NAMES rather than matched by family label — a label rule is unsafe elsewhere (see NSTask).
    "NSScriptObjectSpecifier", "NSIndexSpecifier", "NSMiddleSpecifier", "NSNameSpecifier",
    "NSPositionalSpecifier", "NSPropertySpecifier", "NSRandomSpecifier", "NSRangeSpecifier",
    "NSRelativeSpecifier", "NSUniqueIDSpecifier", "NSWhoseSpecifier",
    # THE `whose`-CLAUSE PREDICATES, the other half of the same machinery.
    "NSScriptWhoseTest", "NSSpecifierTest", "NSLogicalTest",
    # The three Apple-scripting task runners. `NSUserUnixTask` is NOT here: it runs an ordinary Unix
    # script, which is process execution rather than AppleScript, and the user kept it.
    "NSUserScriptTask", "NSUserAppleScriptTask", "NSUserAutomatorTask",
    # XPC.
    "NSXPCConnection", "NSXPCInterface", "NSXPCListener", "NSXPCListenerEndpoint", "NSXPCCoder",
    "NSXPCListenerDelegate", "NSXPCProxyCreating",
    # Spotlight metadata. `NSSpellServer` is the other half of the same plan unit and is KEPT.
    "NSMetadataItem", "NSMetadataQuery", "NSMetadataQueryDelegate",
    "NSMetadataQueryResultGroup", "NSMetadataQueryAttributeValueTuple",
    # Bonjour. Its two CLASSES are already struck as deprecated; this reaches their SERVANTS, which
    # are not deprecated and were left open — the shape §12.5 called a ledger question before a unit.
    "NSNetService", "NSNetServiceBrowser", "NSNetServiceDelegate", "NSNetServiceBrowserDelegate",
))

# Free-standing rows that belong to a declined family without being owned by one of its roots.
DECLINED_SYMBOLS = frozenset((
    "NSNetServiceOptions", "NSNetServicesErrorDomain", "NSNetServicesErrorCode",
))


def is_declined(row):
    """Is this row out by the project's SCOPE DECISION rather than by an Apple fact?

    ASKED ONLY AFTER THE APPLE GROUNDS, so a declined family's deprecated class keeps the specific
    reason Apple gives for it rather than being relabelled."""
    name = row["name"]
    owner = row.get("owner") or ""
    if name in DECLINED_SYMBOLS or owner in DECLINED_SYMBOLS:
        return True
    if name in DECLINED_ROOTS or owner in DECLINED_ROOTS:
        return True
    # THE XPC ERROR CODES live under "User-Relevant Errors" rather than in the XPC family.
    if "XPC" in (row.get("family") or ""):
        return True
    return False


def why_of(row):
    """The `why` column: the reason this row is not simply shipped or open."""
    if row["name"] in REQUIRED_BY_LIVE_API:      # empty today; see above
        return "required-by-live-api"
    return struck_reason(row) or ("declined" if is_declined(row) else "-")


# EVERY strike reason, in one place. The first version of the fourth exclusion
# added a reason without adding it here, and the ledger said so: `func struck`
# fell from 52 to 42 while `func open` rose by the same 10, because ten zone
# functions were carrying a reason the status test did not recognise. A reason
# that does not strike is a row that lies about where it stands.
STRIKE_REASONS = ("32-bit-only", "swift-only", "deprecated", "os-version-constant", "declined")


def status_of(kind, name, why, text):
    if why in STRIKE_REASONS:
        return STATUS_STRUCK
    return STATUS_SHIPPED if declared(kind, name, text) else STATUS_OPEN


def apple_says_deprecated(row):
    """§11.5's test, and it has TWO sources because Apple's documentation is
    internally inconsistent about one of them.

    1. The symbol's own `deprecated` flag in the index — the direct signal.
    2. The group Apple FILES IT UNDER. Some of Foundation's oldest API carries
       no flag at all: `NSURLConnection`'s class node has none, and its page
       reports no `deprecatedAt` either, while every method beneath it is
       flagged — yet Apple puts the whole thing under `Networking / Legacy`.
       A group named Deprecated or Legacy is Apple saying the same thing in the
       other place it has to say it, so it counts."""
    if row["deprecated"]:
        return True
    return any(part.strip() in ("Deprecated", "Legacy") for part in row["family"].split(" / "))


# --------------------------------------------------------------------------
# --refresh: read Apple's index and rewrite the surface file
# --------------------------------------------------------------------------

def fetch_index():
    with urllib.request.urlopen(INDEX_URL, timeout=120) as fh:
        return json.load(fh)


def collect(index):
    """Walk the ObjC navigator tree. A groupMarker among a node's children sets
    the FAMILY for the siblings that FOLLOW it — Apple's own taxonomy — and a
    class or protocol becomes the OWNER of the members beneath it. Returns
    (rows, dropped, swift_seen), where rows is keyed by (kind, name, owner)."""
    rows, dropped, swift_seen = {}, {}, set()
    for root in index["interfaceLanguages"]["occ"]:
        walk(root, [], None, rows, dropped, swift_seen)
    return rows, dropped, swift_seen


def walk(node, trail, owner, rows, dropped, swift_seen):
    """The children of `node`, with the family trail and owner in force when the
    walk arrives here. One function, not two: the top level and a class page
    nest the same way, and this file's first version proved that a duplicated
    pair drifts (the dead twin is what a wrong trail looks like).

    THE ANCHOR IS THE WHOLE OF IT: a groupMarker names the siblings that follow
    it AT ITS OWN DEPTH, so it truncates the trail to the depth this walk
    arrived at and appends itself. Without that truncation every marker from
    every level accumulates, which is the unreadable trail this file shipped
    with for one run ("Strings / Constants / App Support / Undo / Progress")."""
    anchor = len(trail)
    for child in node.get("children", []):
        kind = child.get("type")
        if kind == "groupMarker":
            trail = trail[:anchor] + [child.get("title", "")]
            continue
        path = child.get("path", "")
        swift = ("-swift." in path) or ("/swift." in path)
        ours_path = path.startswith("/documentation/foundation/")
        if kind in DROP_KINDS:
            dropped.setdefault(kind, set()).add(child.get("title", ""))
        elif not ours_path and child.get("title") not in KEEP_ELSEWHERE:
            # Apple's Foundation pages carry a cross-framework index — every
            # notification name in AddressBook, every metadata key in
            # AVFoundation — and those nodes are `external` with a path outside
            # this framework. NSNotification's page alone lists 183 of them.
            dropped.setdefault("other-framework", set()).add(child.get("title", ""))
        elif kind in KINDS:
            # A `swift.` path is NOT "a Swift-only symbol" — MEASURED, AND THE
            # FIRST VERSION OF THIS FILE GOT IT WRONG: an ObjC enum declared with
            # NS_ENUM has its page under `...-swift.enum`, and its members carry
            # their ObjC names (NSByteCountFormatterCountStyleBinary,
            # NSCaseInsensitivePredicateOption, NSConstantValueExpressionType).
            # Dropping them on the path marker hid 363 REAL ObjC symbols from
            # the ledger. Swift-only-ness is decided by the NAME (see
            # struck_reason), and the page-marker count is reported instead.
            if swift:
                swift_seen.add(child.get("title", ""))
            # a class or protocol is not a MEMBER of its enclosing class, so it
            # carries no owner even when Apple nests its page under one
            is_page = kind in ("class", "protocol")
            key = (kind, child.get("title", ""), "" if is_page else (owner or ""))
            row = rows.get(key)
            if row is None or (child.get("deprecated") and not row["deprecated"]):
                rows[key] = {
                    "kind": kind, "name": child.get("title", ""),
                    "owner": "" if is_page else (owner or ""),
                    "deprecated": bool(child.get("deprecated")), "swift": swift,
                    "family": " / ".join(trail),
                }
            elif swift and not row["swift"]:
                row["swift"] = True
        if child.get("children"):
            walk(child, trail,
                 child.get("title", "") if kind in ("class", "protocol") else owner,
                 rows, dropped, swift_seen)


def refresh():
    index = fetch_index()
    rows, dropped, swift_seen = collect(index)
    text = public_header_text()
    out = []
    counts = {}
    reasons = {}
    excepted = 0
    for key in sorted(rows):
        r = rows[key]
        why = why_of(r)
        st = status_of(r["kind"], r["name"], why, text)
        if why == "required-by-live-api" and not declared(r["kind"], r["name"], text):
            raise SystemExit("sweep: REQUIRED_BY_LIVE_API names %r but our headers do not declare it — "
                             "an exception is a claim, and this one is false" % r["name"])
        counts[(r["kind"], st)] = counts.get((r["kind"], st), 0) + 1
        if st == STATUS_STRUCK:
            reasons[why] = reasons.get(why, 0) + 1
        elif why == "required-by-live-api":
            excepted = excepted + 1
        out.append("\t".join((r["kind"], st, r["name"], r["owner"], r["family"], why or "-",
                              "swift-page" if r.get("swift") else "objc")))
    header = [
        "# Foundation's documented surface, against this tree.",
        "# docs/design/foundation-plan.md §11.2 (source 2) and §11.3.1.",
        "# GENERATED by tools/foundation-sweep.py --refresh — do not hand-edit the",
        "# status column; --check fails when it drifts from the headers.",
        "#",
        "# source: " + INDEX_URL,
        "#",
        "# kind\tstatus\tname\towner\tfamily\twhy\tsrc",
        "#",
        "# `src` is the page the name was read from. `swift-page` means Apple documents it",
        "# under a `swift.` path — and it is COUNTED ANYWAY when the name is ObjC-spelled,",
        "# which is the point of the third exclusion's proof (see --check).",
        "#",
        "# excluded dimensions this file deliberately does NOT hold (distinct names):",
        "#   method   %4d documented selectors — §11.2 SOURCE 1's business" % len(dropped.get("method", ())),
        "#   property %4d — likewise" % len(dropped.get("property", ())),
        "#   symbol   %4d — Apple's instance-variable documentation" % len(dropped.get("symbol", ())),
        "#   other    %4d — other frameworks' symbols Apple indexes on a Foundation page" % len(dropped.get("other-framework", ())),
        "#",
        "# counted, NOT excluded: %d distinct names Apple documents on a `swift.` page"
        % len(swift_seen),
        "# but which carry the ObjC spelling. An NS_ENUM's page lives under `-swift.enum`",
        "# and its members keep their ObjC names; this file's first version excluded them",
        "# on the path marker, which hid real ObjC constants from the ledger.",
        "#",
        "# why the struck rows are struck: " + ", ".join("%s %d" % (k, v) for k, v in sorted(reasons.items())),
        "#",
        "# THE NAMED EXCEPTION TO §11.5 (user, 2026-09-18): " + ", ".join(
            "%s (%s)" % (k, v) for k, v in sorted(REQUIRED_BY_LIVE_API.items())),
        "# it keeps its `shipped` status and says so in the `why` column.",
        "#",
        "# counts by kind:",
    ]
    for kind in KINDS:
        got = [counts.get((kind, s), 0) for s in (STATUS_SHIPPED, STATUS_OPEN, STATUS_STRUCK)]
        if sum(got):
            header.append("#   %-10s shipped %4d   open %4d   struck %4d" % (kind, *got))
    open(SURFACE, "w", encoding="utf-8").write("\n".join(header + out) + "\n")
    print("sweep: wrote %s (%d symbols)" % (os.path.relpath(SURFACE, ROOT), len(out)))
    return 0


# --------------------------------------------------------------------------
# --check / --work-list: read the file and hold it to this tree
# --------------------------------------------------------------------------

def read_surface():
    rows = []
    for line in open(SURFACE, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        kind, status, name, owner, family, why, src = line.rstrip("\n").split("\t")
        rows.append((kind, status, name, owner, family, why, src))
    return rows


# THE HEADER'S COUNTS BLOCK, AS A CLAIM (added 2026-09-20, W11). `--refresh` WRITES these lines from the
# rows; `--check` used to verify only the ROWS, so a row flipped by hand left the block reporting an
# older tree — measured at HEAD: the rows said `case shipped 360` and the block said 340, which is
# exactly the rows §25 flipped by hand. It is §27's defect class one level down: a derived measurement
# that nothing re-derives, reading as a measurement while the thing it measures has moved.
HEADER_COUNT_RE = re.compile(
    r"^#\s+(\w+)\s+shipped\s+(\d+)\s+open\s+(\d+)\s+struck\s+(\d+)\s*$", re.M)


def header_counts():
    """{kind: (shipped, open, struck)} as the file's own header claims them."""
    text = open(SURFACE, encoding="utf-8").read()
    return {m.group(1): (int(m.group(2)), int(m.group(3)), int(m.group(4)))
            for m in HEADER_COUNT_RE.finditer(text)}


def check(strict=False):
    """Two kinds of finding, and they are not the same kind of thing.

    INCONSISTENCIES are facts about THIS TREE that the file has out of date: a
    `shipped` row the headers no longer declare, or an `open` row they now do.
    Nobody has to decide anything, so they fail the check.

    POLICY FINDINGS are symbols Apple deprecates that our headers still
    declare. §11.5 says we do not ship those — but what to DO about one is a
    decision (measured case: `NSZone`, which the Legacy-group rule sweeps up and
    which Apple's own NON-deprecated `NSCopying` methods take as a parameter).
    A decision is recorded as a ledger row and kept visible here, not turned
    into a build failure, so they are reported and `--strict` is what makes them
    fail. The ledger row is the record; this is the reminder.
    """
    text = public_header_text()
    rows = read_surface()
    bad, policy = [], []
    counts = {}
    swift_page = 0
    swift_only = []
    for kind, status, name, owner, family, why, src in rows:
        counts[(kind, status)] = counts.get((kind, status), 0) + 1
        found = bool(declared(kind, name, text))
        #
        # §11.5's THIRD EXCLUSION, AND ITS PROOF. Two invariants hold over every
        # row, both checkable from this file alone, and they say exactly what the
        # Swift rule excludes:
        #
        #   1. A row read from a `swift.` page is COUNTED unless its name is not
        #      ObjC-spelled — so the rule never excludes an ObjC symbol merely for
        #      living on a Swift page (which is what the first version got wrong).
        #   2. A `swift-only` row is justified BY ITS NAME: it matches the Swift
        #      interop pattern, or it is not ObjC-shaped at all. So every exclusion
        #      is provable by reading the name, with no judgment in the loop.
        #
        if src == "swift-page":
            swift_page += 1
            if status != STATUS_STRUCK and not is_objc_shaped(name):
                bad.append("SWIFT RULE BROKEN      %-9s %s — read from a swift. page, not ObjC-shaped, "
                           "and NOT struck: the rule must exclude it" % (kind, name))
        if why == "swift-only":
            swift_only.append("%s %s" % (kind, name))
            if not (SWIFT_INTEROP_RE.search(name) or not is_objc_shaped(name)):
                bad.append("UNJUSTIFIED EXCLUSION  %-9s %s — struck as swift-only and neither "
                           "Swift-named nor non-ObjC-shaped" % (kind, name))
        if why == "required-by-live-api" and not found:
            bad.append("FALSE EXCEPTION        %-9s %s — REQUIRED_BY_LIVE_API claims live API needs it and "
                       "our headers do not declare it" % (kind, name))
            continue
        if status == STATUS_SHIPPED and not found:
            bad.append("STALE SHIPPED CLAIM    %-9s %s — the surface file says we ship it and our headers do not declare it" % (kind, name))
        elif status == STATUS_OPEN and found:
            bad.append("PRESENT BUT LISTED OPEN %-8s %s%s — our headers now declare it; flip the row" % (kind, name, (" (member of %s)" % owner) if owner else ""))
        elif status == STATUS_STRUCK and found:
            policy.append("%-9s %s%s [struck: %s]" % (kind, name, (" (member of %s)" % owner) if owner else "", why))
    try:
        plan_text = open(PLAN, encoding="utf-8").read()
    except OSError:
        plan_text = ""
    # THE COUNTS BLOCK, RE-DERIVED. The rows above are the truth; the header is a claim about them, and
    # this is the check that makes it one (see header_counts()).
    for hkind, claimed in sorted(header_counts().items()):
        got = (counts.get((hkind, STATUS_SHIPPED), 0),
               counts.get((hkind, STATUS_OPEN), 0),
               counts.get((hkind, STATUS_STRUCK), 0))
        if claimed != got:
            bad.append("STALE COUNT BLOCK     %-9s the header claims shipped/open/struck %s and the rows "
                       "are %s — fix: tools/foundation-sweep.py --refresh" % (hkind, claimed, got))
    span = _family_span(plan_text)
    if span is None:
        bad.append("PLAN FAMILY TABLE has no GENERATED markers — see tools/foundation-sweep.py --families")
    elif plan_text[span[0]:span[1]] != _family_body():
        bad.append("PLAN FAMILY TABLE is stale against the ledger — fix: "
                   "tools/foundation-sweep.py --families --write")
    kinds = sorted({k for k, _ in counts})
    excepted = [r[2] for r in rows if r[5] == "required-by-live-api"]
    print("foundation-sweep: %d symbols in the ledger%s" % (
        len(rows), (" (%d named exception: %s)" % (len(excepted), ", ".join(excepted))) if excepted else ""))
    for kind in kinds:
        print("  %-10s shipped %4d   open %4d   struck %4d" % (
            kind, counts.get((kind, STATUS_SHIPPED), 0),
            counts.get((kind, STATUS_OPEN), 0), counts.get((kind, STATUS_STRUCK), 0)))
    print("  swift rule: %d row(s) read from a `swift.` page and COUNTED (every one ObjC-shaped);"
          % swift_page)
    print("              %d excluded by NAME%s" % (
        len(swift_only), (" — " + ", ".join(sorted(n.split()[-1] for n in swift_only))[:400]) if swift_only else ""))
    print("              (the tree-level figure — symbols documented ONLY in Apple's Swift view,")
    print("               never read by this tool — is recorded in the surface file's header by --refresh)")
    if policy:
        print("\n%d POLICY FINDING(S) — API this ledger STRIKES that we still declare (a struck row is one" % len(policy))
        print("§11.5 removes: deprecated, swift-only, 32-bit-only, an OS-version constant, or DECLINED BY")
        print("PROJECT DECISION. each needs a ledger row, and --strict is what fails on them):\n")
        for line in policy:
            print("  " + line)
    if bad:
        print("\n%d INCONSISTENCIES:\n" % len(bad))
        for line in bad:
            print("  " + line)
        return 1
    if strict and policy:
        return 1
    print("foundation-sweep: consistent — every shipped name is declared and every open name is absent")
    return 0


def family_rollup():
    """The CLASS/PROTOCOL roll-up per Apple family: what the plan's absent-by-family table says."""
    fams = {}
    for kind, status, name, owner, family, why, src in read_surface():
        if kind not in ("class", "protocol"):
            continue
        key = " / ".join([seg.strip() for seg in family.split(" / ")][:2])
        fams.setdefault(key, {"open": [], "shipped": [], "struck": []})[status].append(name)
    return fams


def _backticked(names):
    return ", ".join("`%s`" % n for n in names)


def render_family_table():
    """The data rows, in Apple's family order, in the voice the hand-written table used:
    `N open`, `N open; M STRUCK: …`, `ALL STRUCK: …`, and — for a family whose classes have all landed —
    `all classes shipped`, which is the row that shows movement instead of hiding it."""
    out = []
    for key in sorted(family_rollup()):
        entry = family_rollup()[key]
        open_names = sorted(entry["open"])
        struck = sorted(entry["struck"])
        if open_names and struck:
            status = "%d open; %d STRUCK: %s" % (len(open_names), len(struck), _backticked(struck))
        elif open_names:
            status = "%d open" % len(open_names)
        elif struck and not entry["shipped"]:
            status = "ALL STRUCK: %s" % _backticked(struck)
        elif struck:
            status = "%d STRUCK: %s" % (len(struck), _backticked(struck))
        else:
            status = "all classes shipped"
        out.append("| **%s** | %s | %s |" % (
            key, status, _backticked(open_names) if open_names else "\u2014"))
    return out


def _family_span(text):
    begin = text.find(FAMILY_BEGIN)
    end = text.find(FAMILY_END)
    if begin < 0 or end < 0:
        return None
    return begin, end + len(FAMILY_END)


def _family_body():
    return "\n".join([FAMILY_BEGIN] + render_family_table() + [FAMILY_END])


def families(write=False):
    """Verify (or rewrite) the plan's family table against the ledger. A STALE table is a fact about this
    tree, so `--check` treats it like any other inconsistency — and says how to fix it."""
    text = open(PLAN, encoding="utf-8").read()
    span = _family_span(text)
    if span is None:
        print("foundation-sweep --families: no GENERATED family block in %s"
              % os.path.relpath(PLAN, ROOT))
        return 1
    want = _family_body()
    if not write:
        have = text[span[0]:span[1]]
        if have == want:
            print("foundation-sweep --families: the plan's family table matches the ledger (%d rows)"
                  % len(render_family_table()))
            return 0
        print("foundation-sweep --families: the plan's family table is STALE. Rows that differ:")
        have_lines = set(have.split("\n"))
        want_lines = set(want.split("\n"))
        for line in sorted(want_lines - have_lines)[:6]:
            print("   ledger says: %s" % line[:160])
        for line in sorted(have_lines - want_lines)[:6]:
            print("   the plan says: %s" % line[:160])
        print("   fix: tools/foundation-sweep.py --families --write")
        return 1
    open(PLAN, "w", encoding="utf-8").write(text[:span[0]] + want + text[span[1]:])
    print("foundation-sweep --families: rewrote the plan's family table (%d rows) from the ledger"
          % len(render_family_table()))
    return 0



# --- --unimplemented: DECLARED BUT NOT IMPLEMENTED ---------------------------------------------------
#
# THE STATIC HALF OF A LESSON THAT COST HOURS. Apple's surface is what the HEADERS declare; what the
# library IMPLEMENTS lives in the .m files; and nothing compared the two. The difference only became
# audible when something CALLED a missing method - and then it was fatal, because NSObject's
# -doesNotRecognizeSelector: ABORTED the process (it raises NSInvalidArgumentException now), so a gap that
# could have been a line in a report killed a guest probe instead. This mode is that report.
#
# TWO KINDS OF HIT ARE NOT GAPS, and the scan WALKS THE HIERARCHY so they do not have to be excused by
# hand: a subclass that implements an inherited declaration (a CLASS CLUSTER - NSNumber's accessors live
# in its number classes, and its base class is abstract), and an implementation that sits in a category in
# another file. What survives that walk is a real gap, and a real gap is either FIXED or WRITTEN DOWN with
# a reason in docs/reference/foundation-unimplemented.txt - the inventory rule this project keeps, "named
# or absent, never silently missing".
UNIMPLEMENTED = os.path.join(ROOT, "docs/reference/foundation-unimplemented.txt")

# A SELECTOR IS NOT ONE IDENTIFIER, and getting this wrong made the first version of this report a liar:
# `- (void)insertChild:(id)child atIndex:(NSUInteger)index` was read as `insertChild`, so a method that
# EXISTS looked missing. The scanner below walks the declaration the way the compiler does - an identifier,
# then either nothing (no arguments) or `:` `(type)` `parameter`, repeated while commas separate the
# keywords - and joins the keywords with their colons.
_METHOD_HEAD = re.compile(r"^\s*[-+]\s*\(([^)]*)\)", re.M)


def _method_selectors(body):
    out = set()
    for head in _METHOD_HEAD.finditer(body):
        i = head.end()
        parts = []
        while True:
            m = re.match(r"\s*([A-Za-z_]\w*)", body[i:])
            if m is None:
                break
            name = m.group(1)
            i += m.end()
            colon = re.match(r"\s*:\s*\(([^)]*)\)", body[i:])
            if colon is None:
                if not parts:
                    out.add(name)
                break
            parts.append(name + ":")
            i += colon.end()
            param = re.match(r"\s*[A-Za-z_]\w*", body[i:])
            if param is not None:
                i += param.end()
            # A DECLARATION SEPARATES ITS KEYWORDS WITH SPACES, NOT COMMAS (commas belong to a CALL):
            # `insertChild:(id)child atIndex:(NSUInteger)index`. So the loop continues while another
            # keyword-and-colon-and-type follows, and stops at the `;`, `{` or `)` that ends the line.
            nxt = re.match(r"\s*([A-Za-z_]\w*)\s*:\s*\(", body[i:])
            if nxt is None:
                break
        if parts:
            out.add("".join(parts))
    return out
_PROP = re.compile(r"@property\s*\(([^)]*)\)\s*[^;]*?([A-Za-z_]\w*)\s*;")
_GETTER = re.compile(r"getter\s*=\s*(\w+)")
_SETTER = re.compile(r"setter\s*=\s*(\w+)")


def _objc_blocks(text, kind):
    """(name, superclass, selectors) for every @<kind> block in one file."""
    for part in text.split("@end"):
        at = part.rfind("@" + kind)
        if at < 0:
            continue
        head = part[at + len(kind) + 1:].strip()
        m = re.match(r"(\w+)", head)
        if m is None:
            continue
        name, rest = m.group(1), head[m.end():]
        sup = ""
        s = re.match(r"\s*:\s*(\w+)", rest)
        if s is not None:
            sup = s.group(1)
        sels = _method_selectors(rest)
        for pm in _PROP.finditer(rest):
            attrs, prop = pm.group(1), pm.group(2)
            g, s = _GETTER.search(attrs), _SETTER.search(attrs)
            sels.add(g.group(1) if g else prop)
            if "readonly" not in attrs:
                sels.add(s.group(1) if s else "set" + prop[0].upper() + prop[1:] + ":")
        yield name, sup, sels


def _macro_stems(text):
    """What a token-paste macro GENERATES, in the two forms an X-macro table uses: `numberWith##NAME`
    (a generated PREFIX) and `NAME##Value` (a generated SUFFIX). Either way the file contains selectors
    that no line of source spells out, which is why a text scan cannot see them and why they are recorded
    as generated rather than reported as gaps. Kept per FILE and applied only to the classes implemented
    in that file: a rule this narrow is a reading of the source, not a blanket excuse."""
    stems, suffixes = set(), set()
    for m in re.finditer(r"([A-Za-z_]\w*)\s*##", text):
        if len(m.group(1)) >= 4:
            stems.add(m.group(1))
    for m in re.finditer(r"##\s*([A-Za-z_]\w*)", text):
        if len(m.group(1)) >= 4:
            suffixes.add(m.group(1))
    return stems, suffixes


def _library_surface():
    declared, supers, implemented = {}, {}, {}
    for path in sorted(glob.glob(HEADERS)):
        for name, sup, sels in _objc_blocks(open(path, errors="ignore").read(), "interface"):
            declared.setdefault(name, set()).update(sels)
            if sup:
                supers.setdefault(name, sup)
    for path in sorted(glob.glob(os.path.join(ROOT, "userland/Foundation/*.m"))):
        text = open(path, errors="ignore").read()
        stems, suffixes = _macro_stems(text)
        in_file = set()
        for name, _sup, sels in _objc_blocks(text, "implementation"):
            implemented.setdefault(name, set()).update(sels)
            in_file.add(name)
        for name in in_file:
            for sel in declared.get(name, ()):
                if any(sel.startswith(stem) for stem in stems) or \
                   any(sel.endswith(suffix) for suffix in suffixes):
                    implemented[name].add(sel)
    return declared, supers, implemented


def _related(supers, name):
    """`name`, everything that inherits FROM it (a CLASS CLUSTER: NSNumber is abstract and its number
    classes implement what it declares), and everything it inherits from (an ANCESTOR's implementation is
    inherited: NSXMLElement declares -insertChild:atIndex: and NSXMLNode implements it). Both directions
    are needed, and getting only one of them made an implemented method look missing."""
    out = {name}
    changed = True
    while changed:
        changed = False
        for cls, sup in supers.items():
            if sup in out and cls not in out:      # a descendant
                out.add(cls)
                changed = True
        for cls in list(out):
            sup = supers.get(cls)
            if sup and sup not in out:             # an ancestor
                out.add(sup)
                changed = True
    return out


def _baseline():
    if not os.path.exists(UNIMPLEMENTED):
        return {}
    out = {}
    for line in open(UNIMPLEMENTED):
        line = line.split("#")[0].strip()
        if line:
            parts = line.split()
            out[(parts[0], parts[1])] = True
    return out


def unimplemented(write=False):
    declared, supers, implemented = _library_surface()
    base = _baseline()
    hits = []
    for cls in sorted(declared):
        if cls.startswith("FN") or not cls[0].isupper():
            continue        # a class name is capitalised; anything else is the scan mis-reading a block
        family = _related(supers, cls)
        have = set()
        for member in family:
            have |= implemented.get(member, set())
        for sel in sorted(declared[cls] - have):
            hits.append((cls, sel))
    new = [h for h in hits if h not in base]
    print("declared selectors with no implementation anywhere in the library: %d" % len(hits))
    print("  baselined (named, with a reason): %d" % (len(hits) - len(new)))
    print("  NEW, and this mode fails on them: %d" % len(new))
    for cls, sel in new:
        print("   %-30s %s" % (cls, sel))
    if write:
        with open(UNIMPLEMENTED, "w") as fh:
            fh.write("# GENERATED by tools/foundation-sweep.py --unimplemented --write -\n")
            fh.write("# do not hand-edit the KEYS; the reason column is yours to fill in.\n")
            fh.write("#\n# A declared selector with no implementation in the library, or in any\n")
            fh.write("# subclass of the class that declares it (a class cluster). Every line needs\n")
            fh.write("# a reason: \"not implemented yet\" is a work item, and anything else is a\n")
            fh.write("# boundary - the two are different, and the file is where that is decided.\n")
            for cls, sel in hits:
                fh.write("%-30s %-40s # not implemented yet\n" % (cls, sel))
        print("baseline written to %s" % UNIMPLEMENTED)
    return 1 if new else 0


def work_list(want=None):
    rows = [r for r in read_surface() if r[1] == STATUS_OPEN and (want is None or r[0] == want)]
    by_family = {}
    for kind, status, name, owner, family, why, src in rows:
        by_family.setdefault(family, []).append((kind, name, owner))
    for family in sorted(by_family):
        members = by_family[family]
        print("\n## %s  (%d)" % (family or "(no family)", len(members)))
        for kind, name, owner in sorted(members, key=lambda m: (m[0], m[1])):
            print("   %-9s %s%s" % (kind, name, ("\t[%s]" % owner) if owner else ""))
    print("\n%d open symbols" % len(rows))
    return 0


def main(argv):
    mode = argv[1] if len(argv) > 1 else "--check"
    if mode == "--refresh":
        rc = refresh()
        if rc == 0:
            rc = check()
        return rc
    if mode == "--check":
        return check()
    if mode == "--strict":
        return check(strict=True)
    if mode == "--families":
        return families(write="--write" in argv[2:])
    if mode == "--unimplemented":
        return unimplemented(write="--write" in argv[2:])
    if mode == "--work-list":
        return work_list(argv[2] if len(argv) > 2 else None)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
