/* EmitsConstruct.h — generated by sterlingc from EmitsConstruct.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@class Shape;

@interface Shape : NSObject

@property (nonatomic, assign) int32_t sides;

- (instancetype)init:(int32_t)sides;
- (int32_t)describe;

@end

@interface Triangle : Shape

@property (nonatomic, assign) int32_t base;

- (instancetype)init:(int32_t)base;

@end

@interface Factory : NSObject

- (Shape *)make:(int32_t)sides;

@end

_Pragma("clang assume_nonnull end")
