/* EmitsSurface.h — generated by sterlingc from EmitsSurface.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@protocol Drawable;
@protocol Printable;

@protocol Printable <Drawable>
- (void)print;
@optional
- (void)preview;
@property (nonatomic, strong) NSString *tag;
@end

@protocol Drawable
- (void)draw;
@end

@interface EmitsSurface : NSObject <Printable>

@property (nonatomic, strong) NSString *title;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, weak) NSObject *owner;
@property (nonatomic, readonly) int32_t weight;

- (NSString *)describe:(NSString *)name;
- (void)print;
- (void)draw;
- (NSString * _Nullable)nullable:(NSString * _Nullable)name;
- (instancetype)shared;

@end

@interface EmitsSurfaceChild : EmitsSurface

- (void)preview;

@end

_Pragma("clang assume_nonnull end")
