/* EmitsInit.h — generated by sterlingc from EmitsInit.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@interface Point2 : NSObject

@property (nonatomic, assign) int32_t x;
@property (nonatomic, assign) int32_t y;

- (instancetype)init:(int32_t)x y:(int32_t)y;
- (int32_t)sum;

@end

_Pragma("clang assume_nonnull end")
