/* EmitsStruct.m — generated by sterlingc from EmitsStruct.ag. Do not edit. */
#import "EmitsStruct.h"

float Point_length(const Point *self)
{
	return self->x + self->y;
}

void Point_moveTo(Point *self, float x, float y)
{
	self->x = x;
	self->y = y;
}

BOOL Point_isOrigin(const Point *self)
{
	return self->x == 0 && self->y == 0;
}

void Point3_moveTo(Point3 *self, float x, float y, float z)
{
	self->x = x;
	self->y = y;
	self->z = z;
}

@implementation Holder

@end
