/* EmitsOptional.m — generated by sterlingc from EmitsOptional.ag. Do not edit. */
#import "EmitsOptional.h"

@implementation Holder

- (SterlingOptional_int32_t)countOr:(SterlingOptional_int32_t)seed
{
	return seed;
}

@end
