/* EmitsUnwrap.m — generated by sterlingc from EmitsUnwrap.ag. Do not edit. */
#import "EmitsUnwrap.h"

@implementation Holder

- (NSString *)shout
{
	return STERLING_UNWRAP(self.name);
}

- (NSString *)shoutTwice
{
	return [STERLING_UNWRAP(self.name) uppercaseString];
}

@end
