/* EmitsConstruct.m — generated by sterlingc from EmitsConstruct.ag. Do not edit. */
#import "EmitsConstruct.h"

@implementation Shape

- (instancetype)init:(int32_t)sides
{
	self.sides = sides;
	return self;
}

- (int32_t)describe
{
	return self.sides;
}

@end

@implementation Triangle

- (instancetype)init:(int32_t)base
{
	self = [super init:3];
	self.base = base;
	return self;
}

@end

@implementation Factory

- (Shape *)make:(int32_t)sides
{
	return [[Shape alloc] init:sides];
}

@end
