/* EmitsEnum.m — generated by sterlingc from EmitsEnum.ag. Do not edit. */
#import "EmitsEnum.h"

@implementation Holder

- (int32_t)pick
{
	return Seeded_a;
}

- (int32_t)dir
{
	return Direction_north;
}

@end
