/* EmitsPair.h — generated by sterlingc from EmitsPair.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@protocol Sink;

@protocol Sink
- (void)receive:(int32_t)value;
@end

@interface EmitsPairFirst : NSObject <Sink>

@property (nonatomic, strong) NSString *label;
@property (nonatomic, readonly) int32_t size;

- (void)receive:(int32_t)value;

@end

@interface EmitsPairSecond : NSObject

@property (nonatomic, assign) int32_t count;

- (int32_t)bump:(int32_t)step;

@end

@interface EmitsPairValues : NSObject

@property (nonatomic, assign) int32_t first;
@property (nonatomic, assign) int32_t second;

@end

_Pragma("clang assume_nonnull end")
