/* EmitsCategory.h — generated by sterlingc from EmitsCategory.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@interface Gauge : NSObject

@property (nonatomic, assign) int32_t level;
@property (nonatomic, strong) NSString *label;

- (void)zero;

@end

@interface Gauge ()

@property (nonatomic, assign) int32_t spare;

- (void)boost;

@end

@interface Gauge (Extra)

- (NSString *)describe;

@end

@interface NSString (Shout)

- (NSString *)shout;

@end

_Pragma("clang assume_nonnull end")
