/* EmitsNested.m — generated by sterlingc from EmitsNested.ag. Do not edit. */
#import "EmitsNested.h"

@implementation Outer_Inner

@end

@implementation Outer

- (Outer_Inner *)make
{
	return self.item;
}

@end

@implementation Standalone

@end
