/* EmitsDefaults.m — generated by sterlingc from EmitsDefaults.ag. Do not edit. */
#import "EmitsDefaults.h"

@implementation Base

- (void)__sterling_defaults
{
	self->_count = 0;
	self->_label = @"hi";
	self->_flag = NO;
}

- (instancetype)init:(int32_t)start
{
	[self __sterling_defaults];
	self.count = start;
	return self;
}

@end

@implementation Sub

- (void)__sterling_defaults
{
	self->_extra = 7;
}

- (instancetype)init:(int32_t)v
{
	self = [super init:v];
	[self __sterling_defaults];
	self.extra = v;
	return self;
}

@end
