/* EmitsCategory.m — generated by sterlingc from EmitsCategory.ag. Do not edit. */
#import "EmitsCategory.h"

@implementation Gauge

- (void)zero
{
	return;
}

- (void)boost
{
	return;
}

@end

@implementation Gauge (Extra)

- (NSString *)describe
{
	return self.label;
}

@end

@implementation NSString (Shout)

- (NSString *)shout
{
	return self;
}

@end
