/* EmitsNesting.m — generated by sterlingc from EmitsNesting.ag. Do not edit. */
#import "EmitsNesting.h"

@implementation EmitsNesting

- (void)classify:(int32_t)scale
{
	int32_t total = scale;
	if (total > 0) {
		total = total - 1;
		while (total > 0) {
			if (total == 1) {
				self.count = 1;
			} else {
				self.count = 2;
			}
			total = total - 1;
		}
	}
	if (total == 0) {
		self.count = 0;
	} else if (total < 0) {
		self.count = -1;
	} else if (total == 1) {
		self.count = 3;
	} else {
	}
}

@end
