/* EmitsOptional.h — generated by sterlingc from EmitsOptional.ag. Do not edit. */
#import <Foundation/Foundation.h>

/* §7.62: a scalar's `?` is a pair-struct, one per scalar used —
   `hasValue` is what `if let`, `x == nil` and `??` read. */
typedef struct { int32_t value; BOOL hasValue; } SterlingOptional_int32_t;
typedef struct { BOOL value; BOOL hasValue; } SterlingOptional_BOOL;
typedef struct { double value; BOOL hasValue; } SterlingOptional_double;

_Pragma("clang assume_nonnull begin")

@class Holder;

typedef struct Span {
	int32_t lo;
	int32_t hi;
} Span;

/* §7.62: a struct's `?` is the same pair-struct, and it is written
   after the struct it wraps, because the member names it. */
typedef struct { Span value; BOOL hasValue; } SterlingOptional_Span;

@interface Holder : NSObject

@property (nonatomic, strong) NSString * _Nullable name;
@property (nonatomic, strong) Holder * _Nullable nickname;
@property (nonatomic, assign) SterlingOptional_int32_t count;
@property (nonatomic, assign) SterlingOptional_BOOL flag;
@property (nonatomic, assign) SterlingOptional_double ratio;
@property (nonatomic, assign) const char * _Nullable cname;
@property (nonatomic, assign) SterlingOptional_Span span;

- (SterlingOptional_int32_t)countOr:(SterlingOptional_int32_t)seed;

@end

_Pragma("clang assume_nonnull end")
