/* EmitsStruct.h — generated by sterlingc from EmitsStruct.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

typedef struct Point {
	float x;
	float y;
} Point;

BOOL Point_isOrigin(const Point *self);
float Point_length(const Point *self);
void Point_moveTo(Point *self, float x, float y);

typedef struct Point3 {
	struct Point;	/* §7.16: the base, at offset 0 */
	float z;
} Point3;

void Point3_moveTo(Point3 *self, float x, float y, float z);

@interface Holder : NSObject

@property (nonatomic, assign) Point origin;

@end

_Pragma("clang assume_nonnull end")
