/* EmitsCore.h — generated by sterlingc from EmitsCore.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@interface EmitsCore : NSObject

@property (nonatomic, assign) int32_t count;
@property (nonatomic, readonly) int32_t limit;

- (void)locals:(int32_t)scale;
+ (void)announce:(BOOL)flag;
- (void)reset;
- (void)report:(NSString *)name total:(int32_t)total;
- (void)scale:(float)half ratio:(double)ratio flag:(BOOL)flag text:(NSString *)text;

@end

_Pragma("clang assume_nonnull end")
