/* EmitsEnum.h — generated by sterlingc from EmitsEnum.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

typedef enum Direction {
	Direction_north,
	Direction_south
} Direction;

typedef enum Seeded {
	Seeded_a = 4,
	Seeded_b = 2,
	Seeded_c
} Seeded;

typedef enum Flags : uint8_t {
	Flags_none,
	Flags_readable
} Flags;

typedef struct Outcome {
	enum {
		Outcome_valueOne = 4,
		Outcome_valueTwo,
		Outcome_valueThree
	} tag;
	union {
		struct { int32_t associateValue; } valueOne;
		struct { double associatedValue; } valueTwo;
		struct { BOOL associatedValueOne; int64_t associatedValueTwo; } valueThree;
	} value;
} Outcome;

@interface Holder : NSObject

- (int32_t)pick;
- (int32_t)dir;

@end

_Pragma("clang assume_nonnull end")
