/* EmitsSurface.m — generated by sterlingc from EmitsSurface.ag. Do not edit. */
#import "EmitsSurface.h"

@implementation EmitsSurface

- (NSString *)describe:(NSString *)name
{
	self.title = name;
	self.label = name;
	self.owner = nil;
	return self.title;
}

- (void)print
{
	return;
}

- (void)draw
{
	return;
}

- (int32_t)weight
{
	return 2;
}

@end
