/* EmitsUnwrap.h — generated by sterlingc from EmitsUnwrap.ag. Do not edit. */
#import <Foundation/Foundation.h>

/* §6/§3.14: `x!` — the language's one piece of runtime behaviour. The
   trap is a BUILTIN rather than an assert, because an NDEBUG-stripped
   assert would silently make `!` non-trapping in an optimised build. */
#define sterlingc_trap_null() __builtin_trap()
#define STERLING_UNWRAP(v) \
	({ __typeof__(v) __sterling_v = (v); \
	if (!__sterling_v) sterlingc_trap_null(); __sterling_v; })

_Pragma("clang assume_nonnull begin")

@interface Holder : NSObject

@property (nonatomic, strong) NSString * _Nullable name;

- (NSString *)shout;
- (NSString *)shoutTwice;

@end

_Pragma("clang assume_nonnull end")
