/* EmitsPair.m — generated by sterlingc from EmitsPair.ag. Do not edit. */
#import "EmitsPair.h"

@implementation EmitsPairFirst

- (void)receive:(int32_t)value
{
	self.label = @"first";
	return;
}

- (int32_t)size
{
	return 1;
}

@end

@implementation EmitsPairSecond

- (int32_t)bump:(int32_t)step
{
	self.count = self.count + step;
	return self.count;
}

@end

@implementation EmitsPairValues

@end
