/* EmitsArray.m — generated by sterlingc from EmitsArray.ag. Do not edit. */
#import "EmitsArray.h"

int32_t EmitsArrayTotal(int32_t const * values)
{
	return 0;
}

double const * EmitsArrayScale(double const * factors)
{
	return factors;
}

@implementation EmitsArray

@end
