/* EmitsNesting.h — generated by sterlingc from EmitsNesting.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@interface EmitsNesting : NSObject

@property (nonatomic, assign) int32_t count;

- (void)classify:(int32_t)scale;

@end

_Pragma("clang assume_nonnull end")
