/* EmitsCore.m — generated by sterlingc from EmitsCore.ag. Do not edit. */
#import "EmitsCore.h"

/* Declared elsewhere; sterlingc imported it. The parameter's name is `arg`. */
extern void callSomeFunc(BOOL arg);

@implementation EmitsCore

- (void)locals:(int32_t)scale
{
	const int32_t base = 2;
	int32_t total = 0;
	const float half = 0.5f;
	const double ratio = 0.25;
	NSString * const name = @"core";
	const NSInteger inferredInt = 3;
	const double inferredFloat = 0.25;
	const BOOL inferredBool = YES;
	NSString * const inferredString = @"text";
	const int32_t doubled = base * 2;
	const int32_t grouped = (base + 2) * 3;
	const int32_t subtracted = 10 - (2 - 1);
	const int32_t negated = -(base + 2);
	const BOOL decided = base > 1 && scale != 0;
	total = doubled + grouped;
	total = total + subtracted;
	total = total + negated;
	total = total + inferredInt;
	self.count = total;
	self.count = self.count + inferredInt;
	if (decided) {
		self.count = 1;
	} else if (total == 4) {
		self.count = 0;
	} else {
		self.count = 4;
	}
	while (self.count < 10) {
		self.count = self.count + 1;
	}
	[self reset];
	[self report:name total:total];
	[self scale:half ratio:ratio flag:inferredBool text:inferredString];
}

+ (void)announce:(BOOL)flag
{
	callSomeFunc(flag);
}

- (void)reset
{
}

- (void)report:(NSString *)name total:(int32_t)total
{
}

- (void)scale:(float)half ratio:(double)ratio flag:(BOOL)flag text:(NSString *)text
{
}

- (int32_t)limit
{
	return 3;
}

@end
