/* EmitsInit.m — generated by sterlingc from EmitsInit.ag. Do not edit. */
#import "EmitsInit.h"

@implementation Point2

- (instancetype)init:(int32_t)x y:(int32_t)y
{
	self.x = x;
	self.y = y;
	return self;
}

- (int32_t)sum
{
	return self.x + self.y;
}

@end
