/* EmitsNested.h — generated by sterlingc from EmitsNested.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@class Outer_Inner;
@class Outer;

@interface Outer_Inner : NSObject

@property (nonatomic, assign) int32_t depth;

@end

@interface Outer : NSObject

@property (nonatomic, strong) Outer_Inner *item;
@property (nonatomic, strong) NSString *label;

- (Outer_Inner *)make;

@end

@interface Standalone : NSObject

@property (nonatomic, strong) Outer *outer;
@property (nonatomic, strong) NSString *note;

@end

_Pragma("clang assume_nonnull end")
