/* EmitsArray.h — generated by sterlingc from EmitsArray.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

typedef struct EmitsArraySpan {
	int32_t lo;
	int32_t hi;
} EmitsArraySpan;

typedef enum EmitsArrayLevel : int32_t {
	EmitsArrayLevel_low = 1,
	EmitsArrayLevel_high
} EmitsArrayLevel;

int32_t EmitsArrayTotal(int32_t const * values);
double const * EmitsArrayScale(double const * factors);

@interface EmitsArray : NSObject

@property (nonatomic, assign) int32_t const *numbers;
@property (nonatomic, assign) EmitsArrayLevel const *levels;
@property (nonatomic, assign) EmitsArraySpan const *spans;
@property (nonatomic, assign) int32_t const * _Nullable maybeNumbers;

@end

_Pragma("clang assume_nonnull end")
