/* EmitsSurface.m — generated by sterlingc from EmitsSurface.ag. Do not edit. */
#import "EmitsSurface.h"

@implementation EmitsSurface

- (NSString *)describe:(NSString *)name
{
	self.title = name;
	self.label = name;
	self.owner = nil;
	return self.title;
}

- (void)print
{
	return;
}

- (void)draw
{
	return;
}

- (NSString * _Nullable)nullable:(NSString * _Nullable)name
{
	NSString * _Nullable const saved = name;
	[self print];
	return saved;
}

- (instancetype)shared
{
	return self;
}

- (int32_t)weight
{
	return 2;
}

@end

@implementation EmitsSurfaceChild

- (void)preview
{
	[super print];
	return;
}

@end
