/* EmitsDefaults.h — generated by sterlingc from EmitsDefaults.ag. Do not edit. */
#import <Foundation/Foundation.h>

_Pragma("clang assume_nonnull begin")

@interface Base : NSObject

@property (nonatomic, assign) int32_t count;
@property (nonatomic, strong) NSString *label;
@property (nonatomic, readonly, assign) BOOL flag;
@property (nonatomic, assign) int32_t plain;

- (instancetype)init:(int32_t)start;

@end

@interface Sub : Base

@property (nonatomic, assign) int32_t extra;

- (instancetype)init:(int32_t)v;

@end

_Pragma("clang assume_nonnull end")
